/* ================================================================
   SISTEMA DE FORMULARIOS DINÁMICOS - SCHEMA COMPLETO + INSERTs
   Versión: 3.0 - Con BIBLIOTECA_COMPONENTE y datos de prueba
   Motor: Oracle Database
   
   CASO DE USO: Formulario 104 - Declaración IVA Mensual SRI Ecuador
   ================================================================ 
revisa a profundidad este diagrama de base de datos que debe servir para crear una aplicación que realiza un diseñador que realiza diseño dinámico de formularios con Oracle 19c y vue, si tienes algo que modificar en el SQL dime, créame un diagrama y una guía del paso a paso para construir este sistema, si puedes hacer un HTML mejor;
 
 revisa a profundidad este diagrama de base de datos, para crear una aplicación que funcione como diseñador que realiza un que realiza diseño dinámico de formularios con stack Oracle 19c. quarkus + panache reactive(withsession y withTransaccion), vue3 + primevue+ pinia + vuevalidate + vuedragable , si tienes algo que modificar en el SQL dime, créame un diagrama y una guía del paso a paso muy detallado para construir este sistema tanto backend como frontend, si puedes hacer un HTML amigable mejor con todas las instrucciones y también con un ejemplo completo de insert sin omitir tablas;
 
 revisa a profundidad este diagrama de base de datos, para crear blueprint para una aplicación que funcione como diseñador que realiza un que realiza diseño dinámico de formularios con stack Oracle 19c, quarkus + panache reactive(withsession y withTransaccion) + arquitectura exagonal + DDD, vue3 + primevue+ pinia + vuevalidate + vuedragable , si tienes algo que modificar en el SQL dime, créame un diagrama ERD y una guía del paso a paso muy detallado para construir este sistema tanto backend como frontend, si puedes crear un HTML amigable con todas las instrucciones y también con un ejemplo completo de insert sin omitir tablas;

haz un analisis profundo de este diagrama de base de datos, para crear blueprint para construir una aplicación que funcione como diseñador que realiza un que realiza diseño dinámico de formularios para el sri con stack (Oracle 19c, quarkus + panache reactive withsession y withTransaccion + arquitectura exagonal y DDD), vue3 + primevue + pinia + vuevalidate + vuedragable + axios, si tienes algo que modificar en el SQL para un sistema diseñador robusto, créame un diagrama ERD y dame una guía del paso a paso bastante detallado para construir este sistema tanto backend como frontend, si puedes crear un HTML amigable con todas las instrucciones y también con un ejemplo completo de insert sin omitir tablas; no inlcuyas la tabla USUARIO; 


 */


/* ================================================================
   MÓDULO 0: SEGURIDAD Y USUARIOS
   ================================================================ */

CREATE TABLE USUARIO (
    CODIGO                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME                VARCHAR2(100) UNIQUE NOT NULL,
    NOMBRE_COMPLETO         VARCHAR2(200) NOT NULL,
    EMAIL                   VARCHAR2(200) UNIQUE NOT NULL,
    HASH_PASSWORD           VARCHAR2(256) NOT NULL,
    SALT                    VARCHAR2(64)  NOT NULL,
    TIPO_AUTENTICACION      VARCHAR2(20)  DEFAULT 'LOCAL',
    ACTIVO                  NUMBER(1)     DEFAULT 1,
    FECHA_CREACION          TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    FECHA_ULTIMO_ACCESO     TIMESTAMP,
    INTENTOS_FALLIDOS       NUMBER        DEFAULT 0,
    BLOQUEADO_HASTA         TIMESTAMP
);

CREATE TABLE ROL (
    CODIGO                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_UNICO            VARCHAR2(50)  UNIQUE NOT NULL,
    NOMBRE                  VARCHAR2(100) NOT NULL,
    DESCRIPCION             VARCHAR2(300),
    ACTIVO                  NUMBER(1)     DEFAULT 1
);

CREATE TABLE PERMISO (
    CODIGO                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_UNICO            VARCHAR2(100) UNIQUE NOT NULL,
    MODULO                  VARCHAR2(50)  NOT NULL,
    ACCION                  VARCHAR2(50)  NOT NULL,
    DESCRIPCION             VARCHAR2(300)
);

CREATE TABLE ROL_PERMISO (
    CODIGO_ROL              NUMBER NOT NULL,
    CODIGO_PERMISO          NUMBER NOT NULL,
    PRIMARY KEY (CODIGO_ROL, CODIGO_PERMISO),
    CONSTRAINT FK_RP_ROL    FOREIGN KEY (CODIGO_ROL)     REFERENCES ROL(CODIGO),
    CONSTRAINT FK_RP_PERM   FOREIGN KEY (CODIGO_PERMISO) REFERENCES PERMISO(CODIGO)
);

CREATE TABLE USUARIO_ROL (
    CODIGO_USUARIO          NUMBER NOT NULL,
    CODIGO_ROL              NUMBER NOT NULL,
    FECHA_ASIGNACION        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ASIGNADO_POR            NUMBER,
    PRIMARY KEY (CODIGO_USUARIO, CODIGO_ROL),
    CONSTRAINT FK_UR_USR    FOREIGN KEY (CODIGO_USUARIO) REFERENCES USUARIO(CODIGO),
    CONSTRAINT FK_UR_ROL    FOREIGN KEY (CODIGO_ROL)     REFERENCES ROL(CODIGO)
);

CREATE TABLE USUARIO_PLANTILLA_ACCESO (
    CODIGO                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_USUARIO          NUMBER NOT NULL,
    CODIGO_PLANTILLA        NUMBER NOT NULL,
    PUEDE_DISENAR              NUMBER(1) DEFAULT 0,
    PUEDE_LLENAR            NUMBER(1) DEFAULT 0,
    PUEDE_REVISAR           NUMBER(1) DEFAULT 0,
    PUEDE_APROBAR           NUMBER(1) DEFAULT 0,
    FECHA_DESDE             DATE      DEFAULT SYSDATE,
    FECHA_HASTA             DATE,
    CONSTRAINT FK_UPA_USR   FOREIGN KEY (CODIGO_USUARIO)   REFERENCES USUARIO(CODIGO),
    CONSTRAINT FK_UPA_PLT   FOREIGN KEY (CODIGO_PLANTILLA) REFERENCES PLANTILLA(CODIGO)
);


/* ================================================================
   MÓDULO 1: TIPOS DE COMPONENTE (Primitivos del Frontend)
   ================================================================ */

-- Catálogo técnico de todos los tipos de componente que el frontend sabe renderizar
CREATE TABLE CATEGORIA_COMPONENTE (
    CODIGO                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IDENTIFICADOR_TECNICO   VARCHAR2(50)  UNIQUE NOT NULL,  -- Ej: 'INPUT_NUMBER', 'SELECT'
    NOMBRE_AMIGABLE         VARCHAR2(100) NOT NULL,
    ICONO_CSS               VARCHAR2(50),
    PERMITE_CATALOGO        NUMBER(1) DEFAULT 0,            -- ¿Puede tener catálogo de origen?
    PERMITE_HIJOS           NUMBER(1) DEFAULT 0,            -- ¿Puede contener otros campos? (GRID, PANEL)
    PERMITE_ADJUNTO         NUMBER(1) DEFAULT 0,            -- ¿Es un campo tipo FILE?
    ACTIVO                  NUMBER(1) DEFAULT 1
);
CREATE INDEX IDX_CP_TIPO ON CATEGORIA_COMPONENTE(IDENTIFICADOR_TECNICO);

-- Biblioteca de componentes preconfigurados (la "caja de herramientas" del diseñador)
-- Un tipo de componente puede tener múltiples widgets en biblioteca con distintas configs
-- Ej: INPUT_NUMBER puede tener "Monto en Dólares", "Porcentaje", "Cantidad Entera"
CREATE TABLE BIBLIOTECA_COMPONENTE (
    CODIGO                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_CATEGORIA_COMPONENTE  NUMBER        NOT NULL,
    NOMBRE_UI               VARCHAR2(100) NOT NULL,          -- Ej: 'Monto en Dólares'
    DESCRIPCION             VARCHAR2(300),
    CATEGORIA_UI            VARCHAR2(50),                    -- Ej: 'Numéricos', 'Fechas', 'Selección'
    ICONO_CSS               VARCHAR2(50),
    -- Config por defecto que se COPIA (snapshot) al campo cuando el diseñador lo arrastra
    -- Ej: {"mask": "currency", "prefix": "$", "decimals": 2, "placeholder": "0.00"}
    CONFIGURACION_DEFAULT_JSON CLOB CONSTRAINT CK_BC_JSON CHECK (CONFIGURACION_DEFAULT_JSON IS JSON),
    ORDEN_CATALOGO          NUMBER DEFAULT 0,
    ACTIVO                  NUMBER(1)     DEFAULT 1,
    CONSTRAINT FK_BC_TIPO   FOREIGN KEY (CODIGO_CATEGORIA_COMPONENTE) REFERENCES CATEGORIA_COMPONENTE(CODIGO)
);


/* ================================================================
   MÓDULO 2: METADATA Y CATÁLOGOS
   ================================================================ */


CREATE TABLE CATEGORIA_PLANTILLA (
    CODIGO                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE                  VARCHAR2(100) NOT NULL,
    DESCRIPCION             VARCHAR2(300),
    ICONO_CSS               VARCHAR2(50),
    ORDEN                   NUMBER DEFAULT 0,
    ACTIVO                  NUMBER(1)     DEFAULT 1
);

CREATE TABLE CATALOGO_MAESTRO (
    CODIGO                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_UNICO            VARCHAR2(50)  UNIQUE NOT NULL,
    NOMBRE                  VARCHAR2(100) NOT NULL,
    DESCRIPCION             VARCHAR2(300),
    METADATA_COLUMNAS_JSON  CLOB CONSTRAINT CK_CAT_META CHECK (METADATA_COLUMNAS_JSON IS JSON),
    PERMITE_JERARQUIA       NUMBER(1)     DEFAULT 0,
    ACTIVO                  NUMBER(1)     DEFAULT 1--,
    --FECHA_CREACION          TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    --USUARIO_CREADOR         NUMBER,
    --CONSTRAINT FK_CM_USR    FOREIGN KEY (USUARIO_CREADOR) REFERENCES USUARIO(CODIGO)
);

CREATE TABLE CATALOGO_DETALLE (
    CODIGO                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_CATALOGO_MAESTRO NUMBER NOT NULL,
    CODIGO_ITEM_PADRE       NUMBER,
    VALOR_CLAVE             VARCHAR2(100) NOT NULL,
    ETIQUETA                VARCHAR2(200) NOT NULL,
    ATRIBUTOS_EXTRA_JSON    CLOB CONSTRAINT CK_CAT_ATTR CHECK (ATRIBUTOS_EXTRA_JSON IS JSON),
    ORDEN                   NUMBER DEFAULT 0,
    ACTIVO                  NUMBER(1)     DEFAULT 1,
    CONSTRAINT FK_CD_MAESTRO FOREIGN KEY (CODIGO_CATALOGO_MAESTRO) REFERENCES CATALOGO_MAESTRO(CODIGO),
    CONSTRAINT FK_CD_PADRE   FOREIGN KEY (CODIGO_ITEM_PADRE)       REFERENCES CATALOGO_DETALLE(CODIGO)
);

CREATE INDEX IDX_CD_MAESTRO ON CATALOGO_DETALLE(CODIGO_CATALOGO_MAESTRO);
CREATE INDEX IDX_CD_PADRE   ON CATALOGO_DETALLE(CODIGO_ITEM_PADRE);
CREATE INDEX IDX_CD_CLAVE   ON CATALOGO_DETALLE(VALOR_CLAVE);


/* ================================================================
   MÓDULO 3: SEMÁNTICA TRIBUTARIA
   ================================================================ */
CREATE TABLE CONCEPTO_TRIBUTARIO (
    CODIGO           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_PADRE     NUMBER,
    CASILLERO_SRI    VARCHAR2(20),
    NOMBRE           VARCHAR2(300) NOT NULL,
    DESCRIPCION      VARCHAR2(500),
    TIPO_DATO        VARCHAR2(50)  DEFAULT 'MONEDA',
    ES_CALCULADO     NUMBER(1)    DEFAULT 0,
    FORMULA_CALCULO  VARCHAR2(500),
    VIGENCIA_DESDE   DATE,
    VIGENCIA_HASTA   DATE,
    ACTIVO           NUMBER(1)    DEFAULT 1,
    CONSTRAINT FK_CT_PAD FOREIGN KEY(CODIGO_PADRE) REFERENCES CONCEPTO_TRIBUTARIO(CODIGO)
);
CREATE INDEX IDX_CT_CASILLERO ON CONCEPTO_TRIBUTARIO(CASILLERO_SRI);


/* ================================================================
   MÓDULO 4: DISEÑADOR DE PLANTILLAS
   ================================================================ */

CREATE TABLE CATEGORIA_PLANTILLA (
    CODIGO      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE      VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(300),
    ICONO_CSS   VARCHAR2(50),
    ORDEN       NUMBER         DEFAULT 0,
    ACTIVO      NUMBER(1)    DEFAULT 1
);

CREATE TABLE PLANTILLA (
    CODIGO                     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_CATEGORIA_PLANTILLA NUMBER        NOT NULL,
    IDENTIFICADOR              VARCHAR2(50)  UNIQUE NOT NULL,
    NOMBRE                     VARCHAR2(200) NOT NULL,
    DESCRIPCION                VARCHAR2(500),
    FECHA_CREACION             TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    USUARIO_CREADOR            NUMBER,
    CONSTRAINT FK_PLT_CAT FOREIGN KEY(CODIGO_CATEGORIA_PLANTILLA) REFERENCES CATEGORIA_PLANTILLA(CODIGO),
    CONSTRAINT FK_PLT_USR FOREIGN KEY(USUARIO_CREADOR)            REFERENCES USUARIO(CODIGO)
);

CREATE TABLE VERSION_PLANTILLA (
    CODIGO           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_PLANTILLA NUMBER        NOT NULL,
    NUMERO_VERSION   VARCHAR2(20)  NOT NULL,
    VIGENCIA_DESDE   DATE          NOT NULL,
    VIGENCIA_HASTA   DATE,
    ESTADO           VARCHAR2(20)  DEFAULT 'BORRADOR',
    CONFIG_GLOBAL_JSON CLOB CONSTRAINT CK_VER_JSON CHECK(CONFIG_GLOBAL_JSON IS JSON),
    FECHA_CREACION   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    USUARIO_CREADOR  NUMBER,
    CONSTRAINT FK_VER_PLT FOREIGN KEY(CODIGO_PLANTILLA)  REFERENCES PLANTILLA(CODIGO),
    CONSTRAINT UK_VER_PLT UNIQUE(CODIGO_PLANTILLA, NUMERO_VERSION),
    CONSTRAINT CK_VER_EST CHECK(ESTADO IN('BORRADOR', 'REVISION', 'APROBADA', 'PUBLICADA', 'OBSOLETA')),
    CONSTRAINT FK_VER_USR FOREIGN KEY(USUARIO_CREADOR) REFERENCES USUARIO(CODIGO)
);

CREATE TABLE VERSION_PLANTILLA_HISTORIAL (
    CODIGO                   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_VERSION_PLANTILLA NUMBER        NOT NULL,
    ESTADO_ANTERIOR          VARCHAR2(20),
    ESTADO_NUEVO             VARCHAR2(20)  NOT NULL,
    COMENTARIO               VARCHAR2(500),
    USUARIO_RESPONSABLE      NUMBER        NOT NULL,
    FECHA_CAMBIO             TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_VPH_VER FOREIGN KEY(CODIGO_VERSION_PLANTILLA) REFERENCES VERSION_PLANTILLA(CODIGO),
    CONSTRAINT FK_VPH_USR FOREIGN KEY(USUARIO_RESPONSABLE)      REFERENCES USUARIO(CODIGO)
);



CREATE TABLE NODO_PLANTILLA (
    CODIGO                       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- ── Contexto (siempre presente) ──────────────────────────────
    CODIGO_VERSION_PLANTILLA     NUMBER        NOT NULL,
    CODIGO_PADRE                 NUMBER,       -- auto-referencia: sección padre o campo grid
    TIPO_NODO                    VARCHAR2(30)  NOT NULL,
    CLAVE_UI                     VARCHAR2(100) NOT NULL,
    ETIQUETA                     VARCHAR2(200),
    DESCRIPCION                  VARCHAR2(500),
    ORDEN                        NUMBER        NOT NULL,

    -- ── Visibilidad / comportamiento básico ──────────────────────
    ES_VISIBLE                   NUMBER(1)    DEFAULT 1,
    ES_EDITABLE                  NUMBER(1)    DEFAULT 1,
    ES_OBLIGATORIO               NUMBER(1)    DEFAULT 0,
    ES_READONLY                  NUMBER(1)    DEFAULT 0,

    -- ── Columnas físicas exclusivas LAYOUT (TIPO_NODO ≠ CAMPO) ──
    ES_COLAPSABLE                NUMBER(1)    DEFAULT 0,
    CONTENIDO_HTML               CLOB,         -- TEXT_BLOCK

    -- ── Columnas físicas exclusivas CAMPO (TIPO_NODO = CAMPO) ───
    CODIGO_CATEGORIA_COMPONENTE  NUMBER,       -- FK → CATEGORIA_COMPONENTE
    CODIGO_BIBLIOTECA_COMPONENTE NUMBER,       -- FK → BIBLIOTECA_COMPONENTE
    CODIGO_CATALOGO_MAESTRO      NUMBER,       -- FK → CATALOGO_MAESTRO (SELECT/RADIO)
    ANCHO_COLUMNAS               NUMBER        DEFAULT 12,  -- grid CSS (1-12)
    PLACEHOLDER                  VARCHAR2(200),
    TEXTO_AYUDA                  VARCHAR2(500),

    -- ── Config JSON (todo lo demás, según tipo) ──────────────────
    --   Layout : { icono, gap, cols, ... }
    --   Campo  : snapshot de BIBLIOTECA_COMPONENTE.CONFIGURACION_DEFAULT_JSON
    --            + personalizaciones del diseñador
    --            Ej: {"mask":"currency","prefix":"$","decimals":2} 
    CONFIG_JSON                  CLOB CONSTRAINT CK_NP_JSON CHECK(CONFIG_JSON IS JSON),

    -- ── Constraints ──────────────────────────────────────────────
    CONSTRAINT CK_NP_TIPO CHECK(
        TIPO_NODO IN(
            'PAGE','TAB','PANEL','SECTION','FIELDSET',
            'TEXT_BLOCK','DIVIDER',
            'CAMPO'
        )
    ),

    -- CAMPO requiere categoría de componente
    CONSTRAINT CK_NP_CAMPO_CAT CHECK(
        TIPO_NODO != 'CAMPO' OR CODIGO_CATEGORIA_COMPONENTE IS NOT NULL
    ),

    -- No-CAMPO no debe tener categoría de componente
    CONSTRAINT CK_NP_LAYOUT_NOCAT CHECK(
        TIPO_NODO = 'CAMPO' OR CODIGO_CATEGORIA_COMPONENTE IS NULL
    ),

    -- CLAVE_UI único por versión
    CONSTRAINT UK_NP_CLAVE UNIQUE(CODIGO_VERSION_PLANTILLA, CLAVE_UI),

    -- FKs
    CONSTRAINT FK_NP_VER    FOREIGN KEY(CODIGO_VERSION_PLANTILLA)    REFERENCES VERSION_PLANTILLA(CODIGO),
    CONSTRAINT FK_NP_PADRE  FOREIGN KEY(CODIGO_PADRE)                 REFERENCES NODO_PLANTILLA(CODIGO),
    CONSTRAINT FK_NP_CATCMP FOREIGN KEY(CODIGO_CATEGORIA_COMPONENTE)  REFERENCES CATEGORIA_COMPONENTE(CODIGO),
    CONSTRAINT FK_NP_BIBLIO FOREIGN KEY(CODIGO_BIBLIOTECA_COMPONENTE) REFERENCES BIBLIOTECA_COMPONENTE(CODIGO),
    CONSTRAINT FK_NP_CATLOG FOREIGN KEY(CODIGO_CATALOGO_MAESTRO)      REFERENCES CATALOGO_MAESTRO(CODIGO)
);

-- Índices
CREATE INDEX IDX_NP_VERSION     ON NODO_PLANTILLA(CODIGO_VERSION_PLANTILLA);
CREATE INDEX IDX_NP_PADRE       ON NODO_PLANTILLA(CODIGO_PADRE);
CREATE INDEX IDX_NP_VER_ORDEN   ON NODO_PLANTILLA(CODIGO_VERSION_PLANTILLA, ORDEN);
CREATE INDEX IDX_NP_TIPO        ON NODO_PLANTILLA(TIPO_NODO);
CREATE INDEX IDX_NP_CATCMP      ON NODO_PLANTILLA(CODIGO_CATEGORIA_COMPONENTE);
CREATE INDEX IDX_NP_CATLOG      ON NODO_PLANTILLA(CODIGO_CATALOGO_MAESTRO);

-- Columnas configurables de un campo tipo GRID / DATATABLE

CREATE TABLE GRID_COLUMNA_PLANTILLA (
    CODIGO                   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    -- FK al nodo de tipo CAMPO cuya CATEGORIA = GRID
    CODIGO_NODO_PLANTILLA    NUMBER        NOT NULL,
    CLAVE_COLUMNA            VARCHAR2(100) NOT NULL,
    CABECERA                 VARCHAR2(200) NOT NULL,
    TIPO_DATO                VARCHAR2(30)  DEFAULT 'TEXT',
    ORDEN                    NUMBER        NOT NULL,
    ANCHO_PX                 NUMBER,
    ES_ORDENABLE             NUMBER(1)    DEFAULT 1,
    ES_FILTRABLE             NUMBER(1)    DEFAULT 0,
    ES_EDITABLE_INLINE       NUMBER(1)    DEFAULT 0,
    CODIGO_CATALOGO_MAESTRO  NUMBER,
    CONFIG_CELDA_JSON        CLOB CONSTRAINT CK_GCP_JSON CHECK(CONFIG_CELDA_JSON IS JSON),
    CONSTRAINT CK_GCP_TIPO  CHECK(TIPO_DATO IN('TEXT','NUMBER','CURRENCY','DATE','BOOLEAN','SELECT')),
    CONSTRAINT FK_GCP_NODO  FOREIGN KEY(CODIGO_NODO_PLANTILLA) REFERENCES NODO_PLANTILLA(CODIGO) ON DELETE CASCADE,
    CONSTRAINT FK_GCP_CAT   FOREIGN KEY(CODIGO_CATALOGO_MAESTRO) REFERENCES CATALOGO_MAESTRO(CODIGO)
);
CREATE INDEX IDX_GCP_NODO ON GRID_COLUMNA_PLANTILLA(CODIGO_NODO_PLANTILLA);

  
--Módulo 4b · Reglas (FK ahora apuntan a NODO_PLANTILLA)
--FK actualizadas → NODO_PLANTILLA
CREATE TABLE REGLA_VALIDACION (
    CODIGO         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE         VARCHAR2(100) NOT NULL,
    TIPO           VARCHAR2(30)  NOT NULL,
    EXPRESION      VARCHAR2(500),
    MENSAJE_ERROR  VARCHAR2(300),
    REUTILIZABLE   NUMBER(1)    DEFAULT 1,
    ACTIVO         NUMBER(1)    DEFAULT 1
);

CREATE TABLE NODO_REGLA_VALIDACION (          -- era CAMPO_REGLA_VALIDACION
    CODIGO_NODO_PLANTILLA   NUMBER NOT NULL,  -- solo nodos TIPO_NODO='CAMPO'
    CODIGO_REGLA_VALIDACION NUMBER NOT NULL,
    ORDEN_EJECUCION         NUMBER DEFAULT 0,
    PARAMETROS_JSON         CLOB CONSTRAINT CK_NRV_JSON CHECK(PARAMETROS_JSON IS JSON),
    PRIMARY KEY(CODIGO_NODO_PLANTILLA, CODIGO_REGLA_VALIDACION),
    CONSTRAINT FK_NRV_NODO  FOREIGN KEY(CODIGO_NODO_PLANTILLA)   REFERENCES NODO_PLANTILLA(CODIGO),
    CONSTRAINT FK_NRV_REGLA FOREIGN KEY(CODIGO_REGLA_VALIDACION) REFERENCES REGLA_VALIDACION(CODIGO)
);

CREATE TABLE REGLA_CONDICIONAL (
    CODIGO               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_NODO_PLANTILLA NUMBER       NOT NULL, -- nodo objetivo de la acción
    ACCION               VARCHAR2(20) NOT NULL,
    CONECTOR_LOGICO      VARCHAR2(5)  DEFAULT 'AND',
    ORDEN                NUMBER        DEFAULT 0,
    CONSTRAINT CK_RC_ACC  CHECK(ACCION IN('SHOW','HIDE','ENABLE','DISABLE','REQUIRE','OPTIONAL','SET_VALUE')),
    CONSTRAINT CK_RC_CON  CHECK(CONECTOR_LOGICO IN('AND','OR')),
    CONSTRAINT FK_RC_NODO FOREIGN KEY(CODIGO_NODO_PLANTILLA) REFERENCES NODO_PLANTILLA(CODIGO)
);

CREATE TABLE REGLA_CONDICIONAL_DETALLE (
    CODIGO                   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_REGLA_CONDICIONAL NUMBER        NOT NULL,
    CLAVE_UI_NODO_EVALUADO   VARCHAR2(100) NOT NULL, -- clave del nodo cuyo valor se evalúa
    OPERADOR                 VARCHAR2(20)  NOT NULL,
    VALOR_REFERENCIA         VARCHAR2(200),
    CONSTRAINT CK_RCD_OP  CHECK(OPERADOR IN('EQUALS','NOT_EQUALS','GREATER_THAN','LESS_THAN','CONTAINS','IS_EMPTY','IS_NOT_EMPTY')),
    CONSTRAINT FK_RCD_RC  FOREIGN KEY(CODIGO_REGLA_CONDICIONAL) REFERENCES REGLA_CONDICIONAL(CODIGO) ON DELETE CASCADE
);

CREATE TABLE NODO_PLANTILLA_CONCEPTO (         -- era CAMPO_PLANTILLA_CONCEPTO
    CODIGO                     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_NODO_PLANTILLA      NUMBER NOT NULL,
    CODIGO_CONCEPTO_TRIBUTARIO NUMBER NOT NULL,
    TIPO_OPERACION             VARCHAR2(20) DEFAULT 'ASIGNACION',
    CONSTRAINT CK_NPC_OP   CHECK(TIPO_OPERACION IN('ASIGNACION','CALCULADO','ACUMULACION')),
    CONSTRAINT FK_NPC_NODO FOREIGN KEY(CODIGO_NODO_PLANTILLA)      REFERENCES NODO_PLANTILLA(CODIGO),
    CONSTRAINT FK_NPC_CON  FOREIGN KEY(CODIGO_CONCEPTO_TRIBUTARIO) REFERENCES CONCEPTO_TRIBUTARIO(CODIGO)
);

/* ================================================================
   MÓDULO 5: EJECUCIÓN
   ================================================================ */
Módulo 5 · Ejecución (sin cambios en estructura, FK renombradas)
FK apuntan a NODO_PLANTILLA donde antes iban a CAMPO_PLANTILLACREATE TABLE FORMULARIO_DECLARACION (
    CODIGO                   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_VERSION_PLANTILLA NUMBER        NOT NULL,
    RUC_CONTRIBUYENTE        VARCHAR2(13)  NOT NULL,
    PERIODO_FISCAL           VARCHAR2(10)  NOT NULL,
    NUMERO_DECLARACION       VARCHAR2(30)  UNIQUE,
    ESTADO                   VARCHAR2(20)  DEFAULT 'BORRADOR',
    PRIORIDAD                VARCHAR2(10)  DEFAULT 'NORMAL',
    DATOS_JSON               CLOB CONSTRAINT CK_DEC_JSON CHECK(DATOS_JSON IS JSON),
    USUARIO_CREADOR          NUMBER,
    FECHA_CREACION           TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    USUARIO_MODIFICADOR      NUMBER,
    FECHA_MODIFICACION       TIMESTAMP,
    USUARIO_ENVIO            NUMBER,
    FECHA_ENVIO              TIMESTAMP,
    CONSTRAINT CK_DEC_EST  CHECK(ESTADO IN('BORRADOR','EN_REVISION','APROBADO','ENVIADO','RECHAZADO')),
    CONSTRAINT FK_DEC_VER  FOREIGN KEY(CODIGO_VERSION_PLANTILLA) REFERENCES VERSION_PLANTILLA(CODIGO),
    CONSTRAINT FK_DEC_UCRE FOREIGN KEY(USUARIO_CREADOR)          REFERENCES USUARIO(CODIGO),
    CONSTRAINT FK_DEC_UMOD FOREIGN KEY(USUARIO_MODIFICADOR)      REFERENCES USUARIO(CODIGO),
    CONSTRAINT FK_DEC_UENV FOREIGN KEY(USUARIO_ENVIO)            REFERENCES USUARIO(CODIGO)
);
CREATE INDEX IDX_DEC_RUC     ON FORMULARIO_DECLARACION(RUC_CONTRIBUYENTE);
CREATE INDEX IDX_DEC_PERIODO ON FORMULARIO_DECLARACION(PERIODO_FISCAL);
CREATE INDEX IDX_DEC_ESTADO  ON FORMULARIO_DECLARACION(ESTADO);

CREATE TABLE DECLARACION_HISTORIAL_ESTADO (
    CODIGO                        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_FORMULARIO_DECLARACION NUMBER        NOT NULL,
    ESTADO_ANTERIOR               VARCHAR2(20),
    ESTADO_NUEVO                  VARCHAR2(20)  NOT NULL,
    COMENTARIO                    VARCHAR2(1000),
    USUARIO_RESPONSABLE           NUMBER        NOT NULL,
    FECHA_CAMBIO                  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_DHE_DEC FOREIGN KEY(CODIGO_FORMULARIO_DECLARACION) REFERENCES FORMULARIO_DECLARACION(CODIGO),
    CONSTRAINT FK_DHE_USR FOREIGN KEY(USUARIO_RESPONSABLE)           REFERENCES USUARIO(CODIGO)
);

CREATE TABLE DETALLE_VALOR_CONCEPTO (
    CODIGO_FORMULARIO_DECLARACION NUMBER NOT NULL,
    CODIGO_CONCEPTO_TRIBUTARIO    NUMBER NOT NULL,
    VALOR_CALCULADO               NUMBER(19,4),
    FECHA_CALCULO                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(CODIGO_FORMULARIO_DECLARACION, CODIGO_CONCEPTO_TRIBUTARIO),
    CONSTRAINT FK_DVC_DEC FOREIGN KEY(CODIGO_FORMULARIO_DECLARACION) REFERENCES FORMULARIO_DECLARACION(CODIGO) ON DELETE CASCADE,
    CONSTRAINT FK_DVC_CON FOREIGN KEY(CODIGO_CONCEPTO_TRIBUTARIO)    REFERENCES CONCEPTO_TRIBUTARIO(CODIGO)
);

CREATE TABLE DECLARACION_OBSERVACION (
    CODIGO                        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_FORMULARIO_DECLARACION NUMBER         NOT NULL,
    CODIGO_NODO_PLANTILLA         NUMBER,        -- era CODIGO_CAMPO_PLANTILLA
    TIPO                          VARCHAR2(20)   DEFAULT 'GENERAL',
    MENSAJE                       VARCHAR2(1000) NOT NULL,
    RESUELTO                      NUMBER(1)      DEFAULT 0,
    USUARIO_CREADOR               NUMBER         NOT NULL,
    FECHA_CREACION                TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    USUARIO_RESOLUTOR             NUMBER,
    FECHA_RESOLUCION              TIMESTAMP,
    CONSTRAINT CK_DO_TIPO  CHECK(TIPO IN('GENERAL','CAMPO','SECCION','CALCULO')),
    CONSTRAINT FK_DO_DEC   FOREIGN KEY(CODIGO_FORMULARIO_DECLARACION) REFERENCES FORMULARIO_DECLARACION(CODIGO),
    CONSTRAINT FK_DO_NODO  FOREIGN KEY(CODIGO_NODO_PLANTILLA)         REFERENCES NODO_PLANTILLA(CODIGO),
    CONSTRAINT FK_DO_UCRE  FOREIGN KEY(USUARIO_CREADOR)               REFERENCES USUARIO(CODIGO),
    CONSTRAINT FK_DO_URES  FOREIGN KEY(USUARIO_RESOLUTOR)             REFERENCES USUARIO(CODIGO)
);

CREATE TABLE DECLARACION_ADJUNTO (
    CODIGO                        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_FORMULARIO_DECLARACION NUMBER        NOT NULL,
    CODIGO_NODO_PLANTILLA         NUMBER,       -- era CODIGO_CAMPO_PLANTILLA
    NOMBRE_ORIGINAL               VARCHAR2(255) NOT NULL,
    NOMBRE_ALMACENADO             VARCHAR2(255) NOT NULL,
    RUTA_ALMACENAMIENTO           VARCHAR2(500) NOT NULL,
    MIME_TYPE                     VARCHAR2(100),
    TAMANO_BYTES                  NUMBER,
    HASH_SHA256                   VARCHAR2(64),
    FECHA_CARGA                   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    USUARIO_CARGA                 NUMBER,
    CONSTRAINT FK_DA_DEC  FOREIGN KEY(CODIGO_FORMULARIO_DECLARACION) REFERENCES FORMULARIO_DECLARACION(CODIGO) ON DELETE CASCADE,
    CONSTRAINT FK_DA_NODO FOREIGN KEY(CODIGO_NODO_PLANTILLA)         REFERENCES NODO_PLANTILLA(CODIGO),
    CONSTRAINT FK_DA_USR  FOREIGN KEY(USUARIO_CARGA)                 REFERENCES USUARIO(CODIGO)
);

--Query CTE recursivo — árbol completo de una versión
-- Oracle SQL · Query-- Carga toda la estructura en una sola query con CONNECT BY
SELECT
    LEVEL                     AS PROFUNDIDAD,
    LPAD(' ', (LEVEL-1)*2) || TIPO_NODO  AS NODO,
    CODIGO,
    CODIGO_PADRE,
    CLAVE_UI,
    ETIQUETA,
    ORDEN,
    TIPO_NODO,
    CODIGO_CATEGORIA_COMPONENTE,
    CONFIG_JSON,
    SYS_CONNECT_BY_PATH(CLAVE_UI, '/')  AS RUTA_UI
FROM  NODO_PLANTILLA
WHERE CODIGO_VERSION_PLANTILLA = :versionId
START WITH  CODIGO_PADRE IS NULL
CONNECT BY  PRIOR CODIGO = CODIGO_PADRE
ORDER SIBLINGS BY ORDEN;

-- -- Workflow de Estados
-- CREATE TABLE CONTROL_FLUJO_ESTADO (
--     CODIGO              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--     CODIGO_VERSION_PLANTILLA NUMBER NOT NULL,
--     ESTADO_ANTERIOR     VARCHAR2(20),
--     ESTADO_NUEVO        VARCHAR2(20) NOT NULL,
--     USUARIO_RESPONSABLE VARCHAR2(100),
--     FECHA_CAMBIO        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     COMENTARIO          VARCHAR2(500),
--     CONSTRAINT FK_CFE_VER FOREIGN KEY (CODIGO_VERSION_PLANTILLA) REFERENCES VERSION_PLANTILLA(CODIGO)
-- );


/* ================================================================
   MÓDULO 6: AUDITORÍA
   ================================================================ */

CREATE TABLE AUDITORIA_LOG (
    CODIGO                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TABLA_AFECTADA          VARCHAR2(100) NOT NULL,
    OPERACION               VARCHAR2(10)  NOT NULL,
    CODIGO_REGISTRO         NUMBER        NOT NULL,
    DATOS_ANTES_JSON        CLOB,
    DATOS_DESPUES_JSON      CLOB,
    USUARIO                 VARCHAR2(100),
    CODIGO_USUARIO          NUMBER,
    IP_ORIGEN               VARCHAR2(45),
    SESION_ID               VARCHAR2(100),
    FECHA                   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_AUDIT_TABLA ON AUDITORIA_LOG(TABLA_AFECTADA);
CREATE INDEX IDX_AUDIT_FECHA ON AUDITORIA_LOG(FECHA);
CREATE INDEX IDX_AUDIT_USR   ON AUDITORIA_LOG(CODIGO_USUARIO);

CREATE TABLE SESION_USUARIO (
    CODIGO                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_USUARIO          NUMBER        NOT NULL,
    TOKEN_SESION            VARCHAR2(256) UNIQUE NOT NULL,
    IP_ORIGEN               VARCHAR2(45),
    USER_AGENT              VARCHAR2(500),
    FECHA_INICIO            TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    FECHA_EXPIRACION        TIMESTAMP     NOT NULL,
    FECHA_CIERRE            TIMESTAMP,
    ESTADO                  VARCHAR2(20)  DEFAULT 'ACTIVA',
    CONSTRAINT FK_SU_USR    FOREIGN KEY (CODIGO_USUARIO) REFERENCES USUARIO(CODIGO)
);


/* ================================================================
   ████████████████████████████████████████████████████████████
   DATOS DE PRUEBA - FLUJO COMPLETO FORMULARIO 104 IVA
   Caso: Empresa ABC declara IVA de Enero 2026
   ████████████████████████████████████████████████████████████
   ================================================================ */


/* ----------------------------------------------------------------
   PASO 1: TIPOS DE COMPONENTE (Primitivos del Frontend)
   ---------------------------------------------------------------- */

INSERT INTO CATEGORIA_COMPONENTE (IDENTIFICADOR_TECNICO, NOMBRE_AMIGABLE, ICONO_CSS, PERMITE_CATALOGO, PERMITE_HIJOS, PERMITE_ADJUNTO) VALUES
('INPUT_TEXT',   'Texto Simple',       'bi-input-cursor-text', 0, 0, 0);

INSERT INTO CATEGORIA_COMPONENTE (IDENTIFICADOR_TECNICO, NOMBRE_AMIGABLE, ICONO_CSS, PERMITE_CATALOGO, PERMITE_HIJOS, PERMITE_ADJUNTO) VALUES
('INPUT_NUMBER', 'Campo Numérico',     'bi-hash',              0, 0, 0);

INSERT INTO CATEGORIA_COMPONENTE (IDENTIFICADOR_TECNICO, NOMBRE_AMIGABLE, ICONO_CSS, PERMITE_CATALOGO, PERMITE_HIJOS, PERMITE_ADJUNTO) VALUES
('SELECT',       'Lista Desplegable',  'bi-chevron-down',      1, 0, 0);

INSERT INTO CATEGORIA_COMPONENTE (IDENTIFICADOR_TECNICO, NOMBRE_AMIGABLE, ICONO_CSS, PERMITE_CATALOGO, PERMITE_HIJOS, PERMITE_ADJUNTO) VALUES
('DATE',         'Selector de Fecha',  'bi-calendar',          0, 0, 0);

INSERT INTO CATEGORIA_COMPONENTE (IDENTIFICADOR_TECNICO, NOMBRE_AMIGABLE, ICONO_CSS, PERMITE_CATALOGO, PERMITE_HIJOS, PERMITE_ADJUNTO) VALUES
('CHECKBOX',     'Casilla de Verificación', 'bi-check2-square', 0, 0, 0);

INSERT INTO CATEGORIA_COMPONENTE (IDENTIFICADOR_TECNICO, NOMBRE_AMIGABLE, ICONO_CSS, PERMITE_CATALOGO, PERMITE_HIJOS, PERMITE_ADJUNTO) VALUES
('LABEL',        'Etiqueta / Resultado', 'bi-tag',             0, 0, 0);

INSERT INTO CATEGORIA_COMPONENTE (IDENTIFICADOR_TECNICO, NOMBRE_AMIGABLE, ICONO_CSS, PERMITE_CATALOGO, PERMITE_HIJOS, PERMITE_ADJUNTO) VALUES
('FILE',         'Carga de Archivo',   'bi-paperclip',         0, 0, 1);

INSERT INTO CATEGORIA_COMPONENTE (IDENTIFICADOR_TECNICO, NOMBRE_AMIGABLE, ICONO_CSS, PERMITE_CATALOGO, PERMITE_HIJOS, PERMITE_ADJUNTO) VALUES
('GRID',         'Tabla de Datos',     'bi-table',             0, 1, 0);

COMMIT;


/* ----------------------------------------------------------------
   PASO 2: BIBLIOTECA_COMPONENTE (La caja de herramientas)
   Widgets preconfigurados que el diseñador arrastra al canvas
   ---------------------------------------------------------------- */

-- Widgets NUMÉRICOS
INSERT INTO BIBLIOTECA_COMPONENTE (CODIGO_CATEGORIA_COMPONENTE, NOMBRE_UI, DESCRIPCION, CATEGORIA_UI, ICONO_CSS, CONFIGURACION_DEFAULT_JSON, ORDEN_CATALOGO) VALUES
(
    (SELECT CODIGO FROM CATEGORIA_COMPONENTE WHERE IDENTIFICADOR_TECNICO = 'INPUT_NUMBER'),
    'Monto en Dólares',
    'Campo monetario con prefijo $, 2 decimales y separador de miles',
    'Numéricos',
    'bi-currency-dollar',
    '{"mask": "currency", "prefix": "$", "decimals": 2, "thousandSeparator": ",", "placeholder": "0.00", "align": "right"}',
    10
);

INSERT INTO BIBLIOTECA_COMPONENTE (CODIGO_CATEGORIA_COMPONENTE, NOMBRE_UI, DESCRIPCION, CATEGORIA_UI, ICONO_CSS, CONFIGURACION_DEFAULT_JSON, ORDEN_CATALOGO) VALUES
(
    (SELECT CODIGO FROM CATEGORIA_COMPONENTE WHERE IDENTIFICADOR_TECNICO = 'INPUT_NUMBER'),
    'Porcentaje (%)',
    'Campo porcentual con sufijo %, rango 0-100',
    'Numéricos',
    'bi-percent',
    '{"mask": "percent", "suffix": "%", "decimals": 2, "min": 0, "max": 100, "placeholder": "0.00", "align": "right"}',
    20
);

INSERT INTO BIBLIOTECA_COMPONENTE (CODIGO_CATEGORIA_COMPONENTE, NOMBRE_UI, DESCRIPCION, CATEGORIA_UI, ICONO_CSS, CONFIGURACION_DEFAULT_JSON, ORDEN_CATALOGO) VALUES
(
    (SELECT CODIGO FROM CATEGORIA_COMPONENTE WHERE IDENTIFICADOR_TECNICO = 'INPUT_NUMBER'),
    'Cantidad Entera',
    'Campo numérico entero sin decimales',
    'Numéricos',
    'bi-123',
    '{"mask": "integer", "decimals": 0, "min": 0, "placeholder": "0", "align": "right"}',
    30
);

-- Widgets de TEXTO
INSERT INTO BIBLIOTECA_COMPONENTE (CODIGO_CATEGORIA_COMPONENTE, NOMBRE_UI, DESCRIPCION, CATEGORIA_UI, ICONO_CSS, CONFIGURACION_DEFAULT_JSON, ORDEN_CATALOGO) VALUES
(
    (SELECT CODIGO FROM CATEGORIA_COMPONENTE WHERE IDENTIFICADOR_TECNICO = 'INPUT_TEXT'),
    'RUC / Identificación',
    'Campo de texto con máscara para RUC (13 dígitos) o cédula (10 dígitos)',
    'Texto',
    'bi-person-badge',
    '{"mask": "ruc", "maxlength": 13, "placeholder": "Ej: 1790012345001", "inputmode": "numeric"}',
    10
);

INSERT INTO BIBLIOTECA_COMPONENTE (CODIGO_CATEGORIA_COMPONENTE, NOMBRE_UI, DESCRIPCION, CATEGORIA_UI, ICONO_CSS, CONFIGURACION_DEFAULT_JSON, ORDEN_CATALOGO) VALUES
(
    (SELECT CODIGO FROM CATEGORIA_COMPONENTE WHERE IDENTIFICADOR_TECNICO = 'INPUT_TEXT'),
    'Texto Libre',
    'Campo de texto sin restricciones de formato',
    'Texto',
    'bi-textarea',
    '{"maxlength": 500, "placeholder": "Ingrese texto..."}',
    20
);

-- Widgets de SELECCIÓN
INSERT INTO BIBLIOTECA_COMPONENTE (CODIGO_CATEGORIA_COMPONENTE, NOMBRE_UI, DESCRIPCION, CATEGORIA_UI, ICONO_CSS, CONFIGURACION_DEFAULT_JSON, ORDEN_CATALOGO) VALUES
(
    (SELECT CODIGO FROM CATEGORIA_COMPONENTE WHERE IDENTIFICADOR_TECNICO = 'SELECT'),
    'Lista Simple',
    'Dropdown de selección única con búsqueda',
    'Selección',
    'bi-list-ul',
    '{"searchable": true, "clearable": true, "placeholder": "Seleccione una opción..."}',
    10
);

INSERT INTO BIBLIOTECA_COMPONENTE (CODIGO_CATEGORIA_COMPONENTE, NOMBRE_UI, DESCRIPCION, CATEGORIA_UI, ICONO_CSS, CONFIGURACION_DEFAULT_JSON, ORDEN_CATALOGO) VALUES
(
    (SELECT CODIGO FROM CATEGORIA_COMPONENTE WHERE IDENTIFICADOR_TECNICO = 'SELECT'),
    'Lista Múltiple',
    'Dropdown de selección múltiple con chips',
    'Selección',
    'bi-ui-checks',
    '{"multiple": true, "searchable": true, "placeholder": "Seleccione opciones..."}',
    20
);

-- Widgets de FECHA
INSERT INTO BIBLIOTECA_COMPONENTE (CODIGO_CATEGORIA_COMPONENTE, NOMBRE_UI, DESCRIPCION, CATEGORIA_UI, ICONO_CSS, CONFIGURACION_DEFAULT_JSON, ORDEN_CATALOGO) VALUES
(
    (SELECT CODIGO FROM CATEGORIA_COMPONENTE WHERE IDENTIFICADOR_TECNICO = 'DATE'),
    'Fecha (DD/MM/YYYY)',
    'Selector de fecha con formato latinoamericano',
    'Fechas',
    'bi-calendar3',
    '{"format": "DD/MM/YYYY", "locale": "es-EC", "placeholder": "DD/MM/AAAA"}',
    10
);

INSERT INTO BIBLIOTECA_COMPONENTE (CODIGO_CATEGORIA_COMPONENTE, NOMBRE_UI, DESCRIPCION, CATEGORIA_UI, ICONO_CSS, CONFIGURACION_DEFAULT_JSON, ORDEN_CATALOGO) VALUES
(
    (SELECT CODIGO FROM CATEGORIA_COMPONENTE WHERE IDENTIFICADOR_TECNICO = 'DATE'),
    'Mes y Año (Período Fiscal)',
    'Selector de mes y año para períodos fiscales',
    'Fechas',
    'bi-calendar-month',
    '{"format": "MM/YYYY", "locale": "es-EC", "placeholder": "MM/AAAA", "granularity": "month"}',
    20
);

-- Widget LABEL (campo calculado/resultado)
INSERT INTO BIBLIOTECA_COMPONENTE (CODIGO_CATEGORIA_COMPONENTE, NOMBRE_UI, DESCRIPCION, CATEGORIA_UI, ICONO_CSS, CONFIGURACION_DEFAULT_JSON, ORDEN_CATALOGO) VALUES
(
    (SELECT CODIGO FROM CATEGORIA_COMPONENTE WHERE IDENTIFICADOR_TECNICO = 'LABEL'),
    'Campo Calculado $',
    'Muestra resultado de fórmula en formato monetario, solo lectura',
    'Calculados',
    'bi-calculator',
    '{"readonly": true, "prefix": "$", "decimals": 2, "style": "font-weight: bold; color: #1a1a2e;", "align": "right"}',
    10
);

-- Widget FILE
INSERT INTO BIBLIOTECA_COMPONENTE (CODIGO_CATEGORIA_COMPONENTE, NOMBRE_UI, DESCRIPCION, CATEGORIA_UI, ICONO_CSS, CONFIGURACION_DEFAULT_JSON, ORDEN_CATALOGO) VALUES
(
    (SELECT CODIGO FROM CATEGORIA_COMPONENTE WHERE IDENTIFICADOR_TECNICO = 'FILE'),
    'Documento de Sustento',
    'Carga de PDF, imagen o Excel como soporte de la declaración',
    'Archivos',
    'bi-file-earmark-arrow-up',
    '{"accept": ".pdf,.jpg,.png,.xlsx", "maxSizeMB": 5, "multiple": false}',
    10
);

COMMIT;


/* ----------------------------------------------------------------
   PASO 3: USUARIOS Y ROLES
   ---------------------------------------------------------------- */

INSERT INTO USUARIO (USERNAME, NOMBRE_COMPLETO, EMAIL, HASH_PASSWORD, SALT, TIPO_AUTENTICACION) VALUES
('admin.sistema', 'Administrador del Sistema', 'admin@empresa.gob.ec', 'HASH_BCRYPT_AQUI_1', 'SALT_1', 'LOCAL');

INSERT INTO USUARIO (USERNAME, NOMBRE_COMPLETO, EMAIL, HASH_PASSWORD, SALT, TIPO_AUTENTICACION) VALUES
('disenador.forms', 'María Pérez', 'mperez@empresa.gob.ec', 'HASH_BCRYPT_AQUI_2', 'SALT_2', 'LOCAL');

INSERT INTO USUARIO (USERNAME, NOMBRE_COMPLETO, EMAIL, HASH_PASSWORD, SALT, TIPO_AUTENTICACION) VALUES
('contribuyente.abc', 'Juan Carlos Mora', 'jmora@empresaabc.com', 'HASH_BCRYPT_AQUI_3', 'SALT_3', 'LOCAL');

INSERT INTO USUARIO (USERNAME, NOMBRE_COMPLETO, EMAIL, HASH_PASSWORD, SALT, TIPO_AUTENTICACION) VALUES
('revisor.sri', 'Carlos Andrade', 'candrade@sri.gob.ec', 'HASH_BCRYPT_AQUI_4', 'SALT_4', 'LDAP');

INSERT INTO ROL (CODIGO_UNICO, NOMBRE, DESCRIPCION) VALUES
('ROL_ADMIN',       'Administrador',  'Acceso total al sistema, gestión de usuarios y configuración');
INSERT INTO ROL (CODIGO_UNICO, NOMBRE, DESCRIPCION) VALUES
('ROL_DISEÑADOR',   'Diseñador',      'Crea y edita plantillas de formularios');
INSERT INTO ROL (CODIGO_UNICO, NOMBRE, DESCRIPCION) VALUES
('ROL_DECLARANTE',  'Declarante',     'Llena y envía formularios de declaración');
INSERT INTO ROL (CODIGO_UNICO, NOMBRE, DESCRIPCION) VALUES
('ROL_REVISOR',     'Revisor',        'Revisa y aprueba declaraciones enviadas');

-- Asignar roles a usuarios
INSERT INTO USUARIO_ROL (CODIGO_USUARIO, CODIGO_ROL) VALUES
((SELECT CODIGO FROM USUARIO WHERE USERNAME = 'admin.sistema'),
 (SELECT CODIGO FROM ROL WHERE CODIGO_UNICO = 'ROL_ADMIN'));

INSERT INTO USUARIO_ROL (CODIGO_USUARIO, CODIGO_ROL) VALUES
((SELECT CODIGO FROM USUARIO WHERE USERNAME = 'disenador.forms'),
 (SELECT CODIGO FROM ROL WHERE CODIGO_UNICO = 'ROL_DISEÑADOR'));

INSERT INTO USUARIO_ROL (CODIGO_USUARIO, CODIGO_ROL) VALUES
((SELECT CODIGO FROM USUARIO WHERE USERNAME = 'contribuyente.abc'),
 (SELECT CODIGO FROM ROL WHERE CODIGO_UNICO = 'ROL_DECLARANTE'));

INSERT INTO USUARIO_ROL (CODIGO_USUARIO, CODIGO_ROL) VALUES
((SELECT CODIGO FROM USUARIO WHERE USERNAME = 'revisor.sri'),
 (SELECT CODIGO FROM ROL WHERE CODIGO_UNICO = 'ROL_REVISOR'));

COMMIT;


/* ----------------------------------------------------------------
   PASO 4: CATÁLOGOS (Datos de referencia)
   ---------------------------------------------------------------- */

-- Catálogo: Tipo de Contribuyente
INSERT INTO CATALOGO_MAESTRO (CODIGO_UNICO, NOMBRE, DESCRIPCION, METADATA_COLUMNAS_JSON, USUARIO_CREADOR) VALUES
(
    'CAT_TIPO_CONTRIBUYENTE',
    'Tipo de Contribuyente',
    'Clasificación del contribuyente para efectos tributarios',
    '[{"columna": "regimen", "titulo": "Régimen", "tipo": "text"}]',
    (SELECT CODIGO FROM USUARIO WHERE USERNAME = 'admin.sistema')
);

INSERT INTO CATALOGO_DETALLE (CODIGO_CATALOGO_MAESTRO, VALOR_CLAVE, ETIQUETA, ATRIBUTOS_EXTRA_JSON, ORDEN) VALUES
((SELECT CODIGO FROM CATALOGO_MAESTRO WHERE CODIGO_UNICO = 'CAT_TIPO_CONTRIBUYENTE'),
 'PERSONA_NATURAL', 'Persona Natural', '{"regimen": "GENERAL"}', 1);

INSERT INTO CATALOGO_DETALLE (CODIGO_CATALOGO_MAESTRO, VALOR_CLAVE, ETIQUETA, ATRIBUTOS_EXTRA_JSON, ORDEN) VALUES
((SELECT CODIGO FROM CATALOGO_MAESTRO WHERE CODIGO_UNICO = 'CAT_TIPO_CONTRIBUYENTE'),
 'PERSONA_JURIDICA', 'Persona Jurídica', '{"regimen": "GENERAL"}', 2);

INSERT INTO CATALOGO_DETALLE (CODIGO_CATALOGO_MAESTRO, VALOR_CLAVE, ETIQUETA, ATRIBUTOS_EXTRA_JSON, ORDEN) VALUES
((SELECT CODIGO FROM CATALOGO_MAESTRO WHERE CODIGO_UNICO = 'CAT_TIPO_CONTRIBUYENTE'),
 'RIMPE_NEGOCIO', 'RIMPE - Negocio Popular', '{"regimen": "RIMPE"}', 3);

-- Catálogo: Forma de Pago
INSERT INTO CATALOGO_MAESTRO (CODIGO_UNICO, NOMBRE, DESCRIPCION, METADATA_COLUMNAS_JSON, USUARIO_CREADOR) VALUES
(
    'CAT_FORMA_PAGO',
    'Forma de Pago',
    'Medios de pago aceptados para liquidación tributaria',
    '[]',
    (SELECT CODIGO FROM USUARIO WHERE USERNAME = 'admin.sistema')
);

INSERT INTO CATALOGO_DETALLE (CODIGO_CATALOGO_MAESTRO, VALOR_CLAVE, ETIQUETA, ORDEN) VALUES
((SELECT CODIGO FROM CATALOGO_MAESTRO WHERE CODIGO_UNICO = 'CAT_FORMA_PAGO'),
 'DEBITO_CUENTA', 'Débito Bancario', 1);

INSERT INTO CATALOGO_DETALLE (CODIGO_CATALOGO_MAESTRO, VALOR_CLAVE, ETIQUETA, ORDEN) VALUES
((SELECT CODIGO FROM CATALOGO_MAESTRO WHERE CODIGO_UNICO = 'CAT_FORMA_PAGO'),
 'EFECTIVO', 'Efectivo en Ventanilla', 2);

INSERT INTO CATALOGO_DETALLE (CODIGO_CATALOGO_MAESTRO, VALOR_CLAVE, ETIQUETA, ORDEN) VALUES
((SELECT CODIGO FROM CATALOGO_MAESTRO WHERE CODIGO_UNICO = 'CAT_FORMA_PAGO'),
 'COMP_ELECTRONICA', 'Compensación Electrónica', 3);

COMMIT;


/* ----------------------------------------------------------------
   PASO 5: CONCEPTOS TRIBUTARIOS (Casilleros F104)
   ---------------------------------------------------------------- */

-- Grupo padre: VENTAS
INSERT INTO CONCEPTO_TRIBUTARIO (CASILLERO_SRI, NOMBRE, TIPO_DATO, ES_CALCULADO, VIGENCIA_DESDE) VALUES
(NULL, 'VENTAS Y OTRAS OPERACIONES', 'GRUPO', 0, DATE '2026-01-01');

-- Casilleros de ventas
INSERT INTO CONCEPTO_TRIBUTARIO (CODIGO_PADRE, CASILLERO_SRI, NOMBRE, TIPO_DATO, ES_CALCULADO, VIGENCIA_DESDE) VALUES
((SELECT CODIGO FROM CONCEPTO_TRIBUTARIO WHERE NOMBRE = 'VENTAS Y OTRAS OPERACIONES'),
 '401', 'Ventas Locales Gravadas Tarifa 15%', 'MONEDA', 0, DATE '2026-01-01');

INSERT INTO CONCEPTO_TRIBUTARIO (CODIGO_PADRE, CASILLERO_SRI, NOMBRE, TIPO_DATO, ES_CALCULADO, VIGENCIA_DESDE) VALUES
((SELECT CODIGO FROM CONCEPTO_TRIBUTARIO WHERE NOMBRE = 'VENTAS Y OTRAS OPERACIONES'),
 '405', 'Ventas Locales Tarifa 0% (IVA)', 'MONEDA', 0, DATE '2026-01-01');

INSERT INTO CONCEPTO_TRIBUTARIO (CODIGO_PADRE, CASILLERO_SRI, NOMBRE, TIPO_DATO, ES_CALCULADO, VIGENCIA_DESDE) VALUES
((SELECT CODIGO FROM CONCEPTO_TRIBUTARIO WHERE NOMBRE = 'VENTAS Y OTRAS OPERACIONES'),
 '407', 'Exportaciones de Bienes', 'MONEDA', 0, DATE '2026-01-01');

-- Casillero calculado: Total Ventas
INSERT INTO CONCEPTO_TRIBUTARIO (CODIGO_PADRE, CASILLERO_SRI, NOMBRE, TIPO_DATO, ES_CALCULADO, FORMULA_CALCULO, VIGENCIA_DESDE) VALUES
((SELECT CODIGO FROM CONCEPTO_TRIBUTARIO WHERE NOMBRE = 'VENTAS Y OTRAS OPERACIONES'),
 '429', 'Total Ventas y Operaciones', 'MONEDA', 1, '{401} + {405} + {407}', DATE '2026-01-01');

-- Grupo: IVA GENERADO
INSERT INTO CONCEPTO_TRIBUTARIO (CASILLERO_SRI, NOMBRE, TIPO_DATO, ES_CALCULADO, VIGENCIA_DESDE) VALUES
(NULL, 'IVA GENERADO EN VENTAS', 'GRUPO', 0, DATE '2026-01-01');

INSERT INTO CONCEPTO_TRIBUTARIO (CODIGO_PADRE, CASILLERO_SRI, NOMBRE, TIPO_DATO, ES_CALCULADO, FORMULA_CALCULO, VIGENCIA_DESDE) VALUES
((SELECT CODIGO FROM CONCEPTO_TRIBUTARIO WHERE NOMBRE = 'IVA GENERADO EN VENTAS'),
 '451', 'IVA Generado en Ventas Tarifa 15%', 'MONEDA', 1, '{401} * 0.15', DATE '2026-01-01');

-- Grupo: IVA EN COMPRAS (Crédito Tributario)
INSERT INTO CONCEPTO_TRIBUTARIO (CASILLERO_SRI, NOMBRE, TIPO_DATO, ES_CALCULADO, VIGENCIA_DESDE) VALUES
(NULL, 'CRÉDITO TRIBUTARIO IVA', 'GRUPO', 0, DATE '2026-01-01');

INSERT INTO CONCEPTO_TRIBUTARIO (CODIGO_PADRE, CASILLERO_SRI, NOMBRE, TIPO_DATO, ES_CALCULADO, VIGENCIA_DESDE) VALUES
((SELECT CODIGO FROM CONCEPTO_TRIBUTARIO WHERE NOMBRE = 'CRÉDITO TRIBUTARIO IVA'),
 '500', 'IVA en Compras Gravadas Tarifa 15%', 'MONEDA', 0, DATE '2026-01-01');

-- Impuesto a pagar (calculado)
INSERT INTO CONCEPTO_TRIBUTARIO (CASILLERO_SRI, NOMBRE, TIPO_DATO, ES_CALCULADO, FORMULA_CALCULO, VIGENCIA_DESDE) VALUES
('601', 'Impuesto a Pagar (IVA)', 'MONEDA', 1, '{451} - {500}', DATE '2026-01-01');

COMMIT;


/* ----------------------------------------------------------------
   PASO 6: ESTRUCTURA DE LA PLANTILLA F104
   ---------------------------------------------------------------- */

INSERT INTO CATEGORIA_PLANTILLA (NOMBRE, DESCRIPCION, ICONO_CSS, ORDEN) VALUES
('IVA', 'Impuesto al Valor Agregado - Declaraciones mensuales', 'bi-receipt', 1);

INSERT INTO PLANTILLA (CODIGO_CATEGORIA_PLANTILLA, IDENTIFICADOR, NOMBRE, DESCRIPCION, USUARIO_CREADOR) VALUES
(
    (SELECT CODIGO FROM CATEGORIA_PLANTILLA WHERE NOMBRE = 'IVA'),
    'F104',
    'Formulario 104 - Declaración Mensual de IVA',
    'Declaración mensual del Impuesto al Valor Agregado para personas naturales y jurídicas',
    (SELECT CODIGO FROM USUARIO WHERE USERNAME = 'disenador.forms')
);

INSERT INTO VERSION_PLANTILLA (CODIGO_PLANTILLA, NUMERO_VERSION, VIGENCIA_DESDE, ESTADO, CONFIG_GLOBAL_JSON, USUARIO_CREADOR) VALUES
(
    (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'),
    'v2026.01',
    DATE '2026-01-01',
    'PUBLICADO',
    '{"theme": "sri-oficial", "logo": "/assets/logo-sri.png", "instrucciones_url": "https://sri.gob.ec/f104", "permite_borrador": true, "max_adjuntos": 10}',
    (SELECT CODIGO FROM USUARIO WHERE USERNAME = 'disenador.forms')
);

COMMIT;

-- Historial: la versión pasó de BORRADOR a PUBLICADO
INSERT INTO VERSION_PLANTILLA_HISTORIAL (CODIGO_VERSION_PLANTILLA, ESTADO_ANTERIOR, ESTADO_NUEVO, COMENTARIO, USUARIO_RESPONSABLE) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01'
     AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    'BORRADOR', 'PUBLICADO',
    'Versión revisada y aprobada para período fiscal 2026',
    (SELECT CODIGO FROM USUARIO WHERE USERNAME = 'admin.sistema')
);

COMMIT;


/* ----------------------------------------------------------------
   PASO 7: SECCIONES DEL FORMULARIO (Tabs/Pestañas)
   ---------------------------------------------------------------- */

-- Sección TAB 1: Identificación
INSERT INTO SECCION_PLANTILLA (CODIGO_VERSION_PLANTILLA, TIPO, CLAVE_UI, ETIQUETA, DESCRIPCION, ORDEN, CONFIG_LAYOUT_JSON) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01'
     AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    'TAB', 'tab_identificacion', 'Identificación', 'Datos del contribuyente y período fiscal', 1,
    '{"columnas": 2, "ancho": "100%"}'
);

-- Sección TAB 2: Ventas
INSERT INTO SECCION_PLANTILLA (CODIGO_VERSION_PLANTILLA, TIPO, CLAVE_UI, ETIQUETA, DESCRIPCION, ORDEN, CONFIG_LAYOUT_JSON) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01'
     AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    'TAB', 'tab_ventas', 'Ventas y Operaciones', 'Resumen de ventas gravadas y no gravadas', 2,
    '{"columnas": 2, "ancho": "100%"}'
);

-- Sección TAB 3: Crédito Tributario
INSERT INTO SECCION_PLANTILLA (CODIGO_VERSION_PLANTILLA, TIPO, CLAVE_UI, ETIQUETA, DESCRIPCION, ORDEN, CONFIG_LAYOUT_JSON) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01'
     AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    'TAB', 'tab_credito', 'Crédito Tributario', 'IVA en compras y crédito disponible', 3,
    '{"columnas": 2, "ancho": "100%"}'
);

-- Sección TAB 4: Liquidación y Pago
INSERT INTO SECCION_PLANTILLA (CODIGO_VERSION_PLANTILLA, TIPO, CLAVE_UI, ETIQUETA, DESCRIPCION, ORDEN, CONFIG_LAYOUT_JSON) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01'
     AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    'TAB', 'tab_liquidacion', 'Liquidación', 'Cálculo final del impuesto a pagar o crédito', 4,
    '{"columnas": 2, "ancho": "100%"}'
);

-- Sub-sección FIELDSET dentro de Ventas: Exportaciones
INSERT INTO SECCION_PLANTILLA (CODIGO_VERSION_PLANTILLA, CODIGO_SECCION_PADRE, TIPO, CLAVE_UI, ETIQUETA, ORDEN, CONFIG_LAYOUT_JSON, VISIBLE_DEFECTO) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01'
     AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    (SELECT CODIGO FROM SECCION_PLANTILLA WHERE CLAVE_UI = 'tab_ventas'
     AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01'
         AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    'FIELDSET', 'fs_exportaciones', 'Exportaciones (solo si aplica)', 1,
    '{"columnas": 2, "colapsable": true}',
    0  -- Oculto por defecto, se muestra condicionalmente
);

COMMIT;


/* ----------------------------------------------------------------
   PASO 8: CAMPOS DEL FORMULARIO
   Cada campo referencia su widget de biblioteca y guarda su config
   ---------------------------------------------------------------- */

-- *** TAB IDENTIFICACIÓN ***

INSERT INTO CAMPO_PLANTILLA (CODIGO_VERSION_PLANTILLA, CODIGO_SECCION, CODIGO_BIBLIOTECA_COMPONENTE, CLAVE_UI, ETIQUETA_UI, CATEGORIA_COMPONENTE, ORDEN, ES_OBLIGATORIO, ANCHO_COLUMNAS, PROPIEDADES_UI_JSON) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    (SELECT CODIGO FROM SECCION_PLANTILLA WHERE CLAVE_UI = 'tab_identificacion' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    (SELECT CODIGO FROM BIBLIOTECA_COMPONENTE WHERE NOMBRE_UI = 'RUC / Identificación'),
    'inp_ruc', 'RUC del Contribuyente', 'INPUT_TEXT', 10, 1, 6,
    '{"mask": "ruc", "maxlength": 13, "placeholder": "Ej: 1790012345001", "inputmode": "numeric", "tooltip": "Ingrese su RUC de 13 dígitos"}'
);

INSERT INTO CAMPO_PLANTILLA (CODIGO_VERSION_PLANTILLA, CODIGO_SECCION, CODIGO_BIBLIOTECA_COMPONENTE, CLAVE_UI, ETIQUETA_UI, CATEGORIA_COMPONENTE, ORDEN, ES_OBLIGATORIO, ANCHO_COLUMNAS, CODIGO_CATALOGO_MAESTRO, PROPIEDADES_UI_JSON) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    (SELECT CODIGO FROM SECCION_PLANTILLA WHERE CLAVE_UI = 'tab_identificacion' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    (SELECT CODIGO FROM BIBLIOTECA_COMPONENTE WHERE NOMBRE_UI = 'Lista Simple'),
    'sel_tipo_contribuyente', 'Tipo de Contribuyente', 'SELECT', 20, 1, 6,
    (SELECT CODIGO FROM CATALOGO_MAESTRO WHERE CODIGO_UNICO = 'CAT_TIPO_CONTRIBUYENTE'),
    '{"searchable": true, "clearable": false, "placeholder": "Seleccione tipo..."}'
);

INSERT INTO CAMPO_PLANTILLA (CODIGO_VERSION_PLANTILLA, CODIGO_SECCION, CODIGO_BIBLIOTECA_COMPONENTE, CLAVE_UI, ETIQUETA_UI, CATEGORIA_COMPONENTE, ORDEN, ES_OBLIGATORIO, ANCHO_COLUMNAS, PROPIEDADES_UI_JSON) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    (SELECT CODIGO FROM SECCION_PLANTILLA WHERE CLAVE_UI = 'tab_identificacion' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    (SELECT CODIGO FROM BIBLIOTECA_COMPONENTE WHERE NOMBRE_UI = 'Mes y Año (Período Fiscal)'),
    'inp_periodo', 'Período Fiscal (Mes/Año)', 'DATE', 30, 1, 6,
    '{"format": "MM/YYYY", "locale": "es-EC", "placeholder": "MM/AAAA", "granularity": "month", "tooltip": "Mes y año de la declaración"}'
);

-- *** TAB VENTAS ***

INSERT INTO CAMPO_PLANTILLA (CODIGO_VERSION_PLANTILLA, CODIGO_SECCION, CODIGO_BIBLIOTECA_COMPONENTE, CLAVE_UI, ETIQUETA_UI, CATEGORIA_COMPONENTE, ORDEN, ES_OBLIGATORIO, ANCHO_COLUMNAS, PROPIEDADES_UI_JSON) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    (SELECT CODIGO FROM SECCION_PLANTILLA WHERE CLAVE_UI = 'tab_ventas' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    (SELECT CODIGO FROM BIBLIOTECA_COMPONENTE WHERE NOMBRE_UI = 'Monto en Dólares'),
    'inp_ventas_grav_15', 'Casillero 401 - Ventas Gravadas Tarifa 15%', 'INPUT_NUMBER', 10, 0, 6,
    '{"mask": "currency", "prefix": "$", "decimals": 2, "thousandSeparator": ",", "placeholder": "0.00", "align": "right", "tooltip": "Total de ventas locales gravadas con IVA del 15%", "casillero": "401"}'
);

INSERT INTO CAMPO_PLANTILLA (CODIGO_VERSION_PLANTILLA, CODIGO_SECCION, CODIGO_BIBLIOTECA_COMPONENTE, CLAVE_UI, ETIQUETA_UI, CATEGORIA_COMPONENTE, ORDEN, ES_OBLIGATORIO, ANCHO_COLUMNAS, PROPIEDADES_UI_JSON) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    (SELECT CODIGO FROM SECCION_PLANTILLA WHERE CLAVE_UI = 'tab_ventas' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    (SELECT CODIGO FROM BIBLIOTECA_COMPONENTE WHERE NOMBRE_UI = 'Monto en Dólares'),
    'inp_ventas_cero', 'Casillero 405 - Ventas Tarifa 0%', 'INPUT_NUMBER', 20, 0, 6,
    '{"mask": "currency", "prefix": "$", "decimals": 2, "thousandSeparator": ",", "placeholder": "0.00", "align": "right", "tooltip": "Ventas locales con tarifa 0% de IVA", "casillero": "405"}'
);

-- Campo en sub-sección de exportaciones (oculto por defecto)
INSERT INTO CAMPO_PLANTILLA (CODIGO_VERSION_PLANTILLA, CODIGO_SECCION, CODIGO_BIBLIOTECA_COMPONENTE, CLAVE_UI, ETIQUETA_UI, CATEGORIA_COMPONENTE, ORDEN, ES_OBLIGATORIO, ANCHO_COLUMNAS, PROPIEDADES_UI_JSON) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    (SELECT CODIGO FROM SECCION_PLANTILLA WHERE CLAVE_UI = 'fs_exportaciones' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    (SELECT CODIGO FROM BIBLIOTECA_COMPONENTE WHERE NOMBRE_UI = 'Monto en Dólares'),
    'inp_exportaciones', 'Casillero 407 - Exportaciones de Bienes', 'INPUT_NUMBER', 10, 0, 6,
    '{"mask": "currency", "prefix": "$", "decimals": 2, "placeholder": "0.00", "align": "right", "casillero": "407"}'
);

-- Campo calculado: Total Ventas (casillero 429)
INSERT INTO CAMPO_PLANTILLA (CODIGO_VERSION_PLANTILLA, CODIGO_SECCION, CODIGO_BIBLIOTECA_COMPONENTE, CLAVE_UI, ETIQUETA_UI, CATEGORIA_COMPONENTE, ORDEN, ES_OBLIGATORIO, ES_EDITABLE, ANCHO_COLUMNAS, PROPIEDADES_UI_JSON) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    (SELECT CODIGO FROM SECCION_PLANTILLA WHERE CLAVE_UI = 'tab_ventas' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    (SELECT CODIGO FROM BIBLIOTECA_COMPONENTE WHERE NOMBRE_UI = 'Campo Calculado $'),
    'lbl_total_ventas', 'Casillero 429 - TOTAL VENTAS Y OPERACIONES', 'LABEL', 30, 0, 0, 6,
    '{"readonly": true, "prefix": "$", "decimals": 2, "style": "font-weight: bold; color: #1a1a2e;", "align": "right", "formula": "{inp_ventas_grav_15} + {inp_ventas_cero} + {inp_exportaciones}", "casillero": "429"}'
);

-- *** TAB CRÉDITO TRIBUTARIO ***

INSERT INTO CAMPO_PLANTILLA (CODIGO_VERSION_PLANTILLA, CODIGO_SECCION, CODIGO_BIBLIOTECA_COMPONENTE, CLAVE_UI, ETIQUETA_UI, CATEGORIA_COMPONENTE, ORDEN, ES_OBLIGATORIO, ANCHO_COLUMNAS, PROPIEDADES_UI_JSON) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    (SELECT CODIGO FROM SECCION_PLANTILLA WHERE CLAVE_UI = 'tab_credito' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    (SELECT CODIGO FROM BIBLIOTECA_COMPONENTE WHERE NOMBRE_UI = 'Monto en Dólares'),
    'inp_iva_compras', 'Casillero 500 - IVA en Compras Tarifa 15%', 'INPUT_NUMBER', 10, 0, 6,
    '{"mask": "currency", "prefix": "$", "decimals": 2, "placeholder": "0.00", "align": "right", "tooltip": "IVA pagado en compras que genera crédito tributario", "casillero": "500"}'
);

-- *** TAB LIQUIDACIÓN ***

-- Campo calculado: IVA generado en ventas (451)
INSERT INTO CAMPO_PLANTILLA (CODIGO_VERSION_PLANTILLA, CODIGO_SECCION, CODIGO_BIBLIOTECA_COMPONENTE, CLAVE_UI, ETIQUETA_UI, CATEGORIA_COMPONENTE, ORDEN, ES_OBLIGATORIO, ES_EDITABLE, ANCHO_COLUMNAS, PROPIEDADES_UI_JSON) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    (SELECT CODIGO FROM SECCION_PLANTILLA WHERE CLAVE_UI = 'tab_liquidacion' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    (SELECT CODIGO FROM BIBLIOTECA_COMPONENTE WHERE NOMBRE_UI = 'Campo Calculado $'),
    'lbl_iva_generado', 'Casillero 451 - IVA Generado en Ventas 15%', 'LABEL', 10, 0, 0, 6,
    '{"readonly": true, "prefix": "$", "decimals": 2, "style": "font-weight: bold;", "formula": "{inp_ventas_grav_15} * 0.15", "casillero": "451"}'
);

-- Campo calculado: Impuesto a pagar (601)
INSERT INTO CAMPO_PLANTILLA (CODIGO_VERSION_PLANTILLA, CODIGO_SECCION, CODIGO_BIBLIOTECA_COMPONENTE, CLAVE_UI, ETIQUETA_UI, CATEGORIA_COMPONENTE, ORDEN, ES_OBLIGATORIO, ES_EDITABLE, ANCHO_COLUMNAS, PROPIEDADES_UI_JSON) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    (SELECT CODIGO FROM SECCION_PLANTILLA WHERE CLAVE_UI = 'tab_liquidacion' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    (SELECT CODIGO FROM BIBLIOTECA_COMPONENTE WHERE NOMBRE_UI = 'Campo Calculado $'),
    'lbl_impuesto_pagar', 'Casillero 601 - IMPUESTO A PAGAR', 'LABEL', 20, 0, 0, 6,
    '{"readonly": true, "prefix": "$", "decimals": 2, "style": "font-weight: bold; font-size: 1.2em; color: #c0392b;", "formula": "{lbl_iva_generado} - {inp_iva_compras}", "casillero": "601"}'
);

-- Campo: Forma de pago
INSERT INTO CAMPO_PLANTILLA (CODIGO_VERSION_PLANTILLA, CODIGO_SECCION, CODIGO_BIBLIOTECA_COMPONENTE, CLAVE_UI, ETIQUETA_UI, CATEGORIA_COMPONENTE, ORDEN, ES_OBLIGATORIO, ANCHO_COLUMNAS, CODIGO_CATALOGO_MAESTRO, PROPIEDADES_UI_JSON) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    (SELECT CODIGO FROM SECCION_PLANTILLA WHERE CLAVE_UI = 'tab_liquidacion' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    (SELECT CODIGO FROM BIBLIOTECA_COMPONENTE WHERE NOMBRE_UI = 'Lista Simple'),
    'sel_forma_pago', 'Forma de Pago', 'SELECT', 30, 1, 6,
    (SELECT CODIGO FROM CATALOGO_MAESTRO WHERE CODIGO_UNICO = 'CAT_FORMA_PAGO'),
    '{"searchable": false, "clearable": false, "placeholder": "Seleccione forma de pago..."}'
);

-- Campo: Adjunto de sustento
INSERT INTO CAMPO_PLANTILLA (CODIGO_VERSION_PLANTILLA, CODIGO_SECCION, CODIGO_BIBLIOTECA_COMPONENTE, CLAVE_UI, ETIQUETA_UI, CATEGORIA_COMPONENTE, ORDEN, ES_OBLIGATORIO, ANCHO_COLUMNAS, PROPIEDADES_UI_JSON) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    (SELECT CODIGO FROM SECCION_PLANTILLA WHERE CLAVE_UI = 'tab_liquidacion' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    (SELECT CODIGO FROM BIBLIOTECA_COMPONENTE WHERE NOMBRE_UI = 'Documento de Sustento'),
    'file_sustento', 'Documento de Sustento (opcional)', 'FILE', 40, 0, 12,
    '{"accept": ".pdf,.jpg,.png,.xlsx", "maxSizeMB": 5, "multiple": false, "hint": "Adjunte el reporte de ventas o libro de IVA"}'
);

COMMIT;


/* ----------------------------------------------------------------
   PASO 9: REGLAS DE VALIDACIÓN Y CONDICIONES
   ---------------------------------------------------------------- */

-- Regla reutilizable: RUC válido Ecuador
INSERT INTO REGLA_VALIDACION (NOMBRE, TIPO, EXPRESION, MENSAJE_ERROR, REUTILIZABLE) VALUES
('ruc_ecuador_valido', 'REGEX', '^\d{10}(001)$', 'El RUC debe tener 13 dígitos y terminar en 001', 1);

-- Regla reutilizable: Valor no negativo
INSERT INTO REGLA_VALIDACION (NOMBRE, TIPO, EXPRESION, MENSAJE_ERROR, REUTILIZABLE) VALUES
('monto_no_negativo', 'RANGO', NULL, 'El monto no puede ser negativo', 1);

-- Asignar regla de RUC al campo inp_ruc
INSERT INTO CAMPO_REGLA_VALIDACION (CODIGO_CAMPO_PLANTILLA, CODIGO_REGLA_VALIDACION, ORDEN_EJECUCION, PARAMETROS_JSON) VALUES
(
    (SELECT CODIGO FROM CAMPO_PLANTILLA WHERE CLAVE_UI = 'inp_ruc' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    (SELECT CODIGO FROM REGLA_VALIDACION WHERE NOMBRE = 'ruc_ecuador_valido'),
    1, '{}'
);

-- Asignar regla de monto no negativo a ventas
INSERT INTO CAMPO_REGLA_VALIDACION (CODIGO_CAMPO_PLANTILLA, CODIGO_REGLA_VALIDACION, ORDEN_EJECUCION, PARAMETROS_JSON) VALUES
(
    (SELECT CODIGO FROM CAMPO_PLANTILLA WHERE CLAVE_UI = 'inp_ventas_grav_15' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    (SELECT CODIGO FROM REGLA_VALIDACION WHERE NOMBRE = 'monto_no_negativo'),
    1, '{"min": 0, "max": 9999999.99}'
);

-- Regla condicional: Si tipo_contribuyente = PERSONA_JURIDICA → mostrar sección exportaciones
INSERT INTO REGLA_CONDICIONAL (CODIGO_CAMPO_PLANTILLA, ACCION, CONECTOR_LOGICO) VALUES
(
    -- Afecta al campo inp_exportaciones (que está en fs_exportaciones)
    (SELECT CODIGO FROM CAMPO_PLANTILLA WHERE CLAVE_UI = 'inp_exportaciones' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    'MOSTRAR', 'AND'
);

INSERT INTO REGLA_CONDICIONAL_DETALLE (CODIGO_REGLA_CONDICIONAL, CLAVE_UI_CAMPO_EVALUADO, OPERADOR, VALOR_REFERENCIA) VALUES
(
    (SELECT MAX(CODIGO) FROM REGLA_CONDICIONAL),
    'sel_tipo_contribuyente', 'IGUAL', 'PERSONA_JURIDICA'
);

COMMIT;


/* ----------------------------------------------------------------
   PASO 10: MAPEO SEMÁNTICO (Campos → Casilleros SRI)
   ---------------------------------------------------------------- */

INSERT INTO CAMPO_PLANTILLA_CONCEPTO (CODIGO_CAMPO_PLANTILLA, CODIGO_CONCEPTO_TRIBUTARIO, TIPO_OPERACION) VALUES
(
    (SELECT CODIGO FROM CAMPO_PLANTILLA WHERE CLAVE_UI = 'inp_ventas_grav_15' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    (SELECT CODIGO FROM CONCEPTO_TRIBUTARIO WHERE CASILLERO_SRI = '401'),
    'ASIGNACION'
);

INSERT INTO CAMPO_PLANTILLA_CONCEPTO (CODIGO_CAMPO_PLANTILLA, CODIGO_CONCEPTO_TRIBUTARIO, TIPO_OPERACION) VALUES
(
    (SELECT CODIGO FROM CAMPO_PLANTILLA WHERE CLAVE_UI = 'inp_ventas_cero' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    (SELECT CODIGO FROM CONCEPTO_TRIBUTARIO WHERE CASILLERO_SRI = '405'),
    'ASIGNACION'
);

INSERT INTO CAMPO_PLANTILLA_CONCEPTO (CODIGO_CAMPO_PLANTILLA, CODIGO_CONCEPTO_TRIBUTARIO, TIPO_OPERACION) VALUES
(
    (SELECT CODIGO FROM CAMPO_PLANTILLA WHERE CLAVE_UI = 'inp_exportaciones' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    (SELECT CODIGO FROM CONCEPTO_TRIBUTARIO WHERE CASILLERO_SRI = '407'),
    'ASIGNACION'
);

INSERT INTO CAMPO_PLANTILLA_CONCEPTO (CODIGO_CAMPO_PLANTILLA, CODIGO_CONCEPTO_TRIBUTARIO, TIPO_OPERACION) VALUES
(
    (SELECT CODIGO FROM CAMPO_PLANTILLA WHERE CLAVE_UI = 'inp_iva_compras' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    (SELECT CODIGO FROM CONCEPTO_TRIBUTARIO WHERE CASILLERO_SRI = '500'),
    'ASIGNACION'
);

COMMIT;


/* ----------------------------------------------------------------
   PASO 11: DECLARACIÓN DEL CONTRIBUYENTE
   Empresa ABC S.A. declara IVA de Enero 2026
   ---------------------------------------------------------------- */

INSERT INTO FORMULARIO_DECLARACION (
    CODIGO_VERSION_PLANTILLA, RUC_CONTRIBUYENTE, PERIODO_FISCAL,
    ESTADO, USUARIO_CREADOR,
    DATOS_JSON
) VALUES
(
    (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01'
     AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104')),
    '1790012345001',
    '2026-01',
    'EN_REVISION',
    (SELECT CODIGO FROM USUARIO WHERE USERNAME = 'contribuyente.abc'),
    '{
        "inp_ruc":               "1790012345001",
        "sel_tipo_contribuyente": "PERSONA_JURIDICA",
        "inp_periodo":           "01/2026",
        "inp_ventas_grav_15":    125000.00,
        "inp_ventas_cero":       30000.00,
        "inp_exportaciones":     45000.00,
        "lbl_total_ventas":      200000.00,
        "inp_iva_compras":       10500.00,
        "lbl_iva_generado":      18750.00,
        "lbl_impuesto_pagar":    8250.00,
        "sel_forma_pago":        "DEBITO_CUENTA"
    }'
);

COMMIT;

-- Historial de estados de la declaración
INSERT INTO DECLARACION_HISTORIAL (CODIGO_FORMULARIO_DECLARACION, ESTADO_ANTERIOR, ESTADO_NUEVO, COMENTARIO, USUARIO_RESPONSABLE) VALUES
(
    (SELECT CODIGO FROM FORMULARIO_DECLARACION WHERE RUC_CONTRIBUYENTE = '1790012345001' AND PERIODO_FISCAL = '2026-01'),
    'BORRADOR', 'EN_REVISION',
    'Declaración completada y enviada para revisión',
    (SELECT CODIGO FROM USUARIO WHERE USERNAME = 'contribuyente.abc')
);

COMMIT;


/* ----------------------------------------------------------------
   PASO 12: VALORES ANALÍTICOS POR CONCEPTO (Tabla de reportes)
   ---------------------------------------------------------------- */

INSERT INTO DETALLE_VALOR_CONCEPTO (CODIGO_FORMULARIO_DECLARACION, CODIGO_CONCEPTO_TRIBUTARIO, VALOR_CALCULADO) VALUES
((SELECT CODIGO FROM FORMULARIO_DECLARACION WHERE RUC_CONTRIBUYENTE = '1790012345001' AND PERIODO_FISCAL = '2026-01'),
 (SELECT CODIGO FROM CONCEPTO_TRIBUTARIO WHERE CASILLERO_SRI = '401'), 125000.00);

INSERT INTO DETALLE_VALOR_CONCEPTO (CODIGO_FORMULARIO_DECLARACION, CODIGO_CONCEPTO_TRIBUTARIO, VALOR_CALCULADO) VALUES
((SELECT CODIGO FROM FORMULARIO_DECLARACION WHERE RUC_CONTRIBUYENTE = '1790012345001' AND PERIODO_FISCAL = '2026-01'),
 (SELECT CODIGO FROM CONCEPTO_TRIBUTARIO WHERE CASILLERO_SRI = '405'), 30000.00);

INSERT INTO DETALLE_VALOR_CONCEPTO (CODIGO_VERSION_PLANTILLA, CODIGO_CONCEPTO_TRIBUTARIO, VALOR_CALCULADO) VALUES
((SELECT CODIGO FROM FORMULARIO_DECLARACION WHERE RUC_CONTRIBUYENTE = '1790012345001' AND PERIODO_FISCAL = '2026-01'),
 (SELECT CODIGO FROM CONCEPTO_TRIBUTARIO WHERE CASILLERO_SRI = '407'), 45000.00);

INSERT INTO DETALLE_VALOR_CONCEPTO (CODIGO_FORMULARIO_DECLARACION, CODIGO_CONCEPTO_TRIBUTARIO, VALOR_CALCULADO) VALUES
((SELECT CODIGO FROM FORMULARIO_DECLARACION WHERE RUC_CONTRIBUYENTE = '1790012345001' AND PERIODO_FISCAL = '2026-01'),
 (SELECT CODIGO FROM CONCEPTO_TRIBUTARIO WHERE CASILLERO_SRI = '429'), 200000.00);  -- calculado

INSERT INTO DETALLE_VALOR_CONCEPTO (CODIGO_FORMULARIO_DECLARACION, CODIGO_CONCEPTO_TRIBUTARIO, VALOR_CALCULADO) VALUES
((SELECT CODIGO FROM FORMULARIO_DECLARACION WHERE RUC_CONTRIBUYENTE = '1790012345001' AND PERIODO_FISCAL = '2026-01'),
 (SELECT CODIGO FROM CONCEPTO_TRIBUTARIO WHERE CASILLERO_SRI = '451'), 18750.00);   -- 125000 * 0.15

INSERT INTO DETALLE_VALOR_CONCEPTO (CODIGO_FORMULARIO_DECLARACION, CODIGO_CONCEPTO_TRIBUTARIO, VALOR_CALCULADO) VALUES
((SELECT CODIGO FROM FORMULARIO_DECLARACION WHERE RUC_CONTRIBUYENTE = '1790012345001' AND PERIODO_FISCAL = '2026-01'),
 (SELECT CODIGO FROM CONCEPTO_TRIBUTARIO WHERE CASILLERO_SRI = '500'), 10500.00);

INSERT INTO DETALLE_VALOR_CONCEPTO (CODIGO_FORMULARIO_DECLARACION, CODIGO_CONCEPTO_TRIBUTARIO, VALOR_CALCULADO) VALUES
((SELECT CODIGO FROM FORMULARIO_DECLARACION WHERE RUC_CONTRIBUYENTE = '1790012345001' AND PERIODO_FISCAL = '2026-01'),
 (SELECT CODIGO FROM CONCEPTO_TRIBUTARIO WHERE CASILLERO_SRI = '601'), 8250.00);    -- 18750 - 10500

COMMIT;


/* ----------------------------------------------------------------
   PASO 13: OBSERVACIÓN DEL REVISOR + ADJUNTO
   ---------------------------------------------------------------- */

INSERT INTO DECLARACION_OBSERVACION (CODIGO_FORMULARIO_DECLARACION, CODIGO_CAMPO_PLANTILLA, TIPO, MENSAJE, USUARIO_CREADOR) VALUES
(
    (SELECT CODIGO FROM FORMULARIO_DECLARACION WHERE RUC_CONTRIBUYENTE = '1790012345001' AND PERIODO_FISCAL = '2026-01'),
    (SELECT CODIGO FROM CAMPO_PLANTILLA WHERE CLAVE_UI = 'inp_exportaciones' AND CODIGO_VERSION_PLANTILLA = (SELECT CODIGO FROM VERSION_PLANTILLA WHERE NUMERO_VERSION = 'v2026.01' AND CODIGO_PLANTILLA = (SELECT CODIGO FROM PLANTILLA WHERE IDENTIFICADOR = 'F104'))),
    'ADVERTENCIA',
    'El monto de exportaciones ($45,000) excede el promedio histórico del contribuyente. Adjunte documentación de sustento (DAEs).',
    (SELECT CODIGO FROM USUARIO WHERE USERNAME = 'revisor.sri')
);

INSERT INTO DECLARACION_ADJUNTO (CODIGO_FORMULARIO_DECLARACION, NOMBRE_ORIGINAL, NOMBRE_ALMACENADO, RUTA_ALMACENAMIENTO, MIME_TYPE, TAMANO_BYTES, HASH_SHA256, USUARIO_CARGA) VALUES
(
    (SELECT CODIGO FROM FORMULARIO_DECLARACION WHERE RUC_CONTRIBUYENTE = '1790012345001' AND PERIODO_FISCAL = '2026-01'),
    'ReporteVentas_Enero2026.pdf',
    'a3f8c2d1-9b45-4e12-8f7a-23b4e56d78c9.pdf',
    '/storage/declaraciones/2026/01/1790012345001/',
    'application/pdf',
    245760,
    'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    (SELECT CODIGO FROM USUARIO WHERE USERNAME = 'contribuyente.abc')
);

COMMIT;


/* ================================================================
   CONSULTAS DE VERIFICACIÓN
   ================================================================ */

-- 1. Ver toda la estructura de la plantilla F104 v2026.01
SELECT
    s.TIPO           AS tipo_seccion,
    s.ETIQUETA       AS seccion,
    cp.ORDEN,
    cp.CLAVE_UI,
    cp.ETIQUETA_UI,
    cp.CATEGORIA_COMPONENTE,
    cp.ES_OBLIGATORIO,
    cp.ANCHO_COLUMNAS,
    bc.NOMBRE_UI     AS widget_biblioteca,
    cm.CODIGO_UNICO  AS catalogo_fuente
FROM CAMPO_PLANTILLA cp
JOIN VERSION_PLANTILLA vp  ON vp.CODIGO = cp.CODIGO_VERSION_PLANTILLA
JOIN PLANTILLA p           ON p.CODIGO  = vp.CODIGO_PLANTILLA
LEFT JOIN SECCION_PLANTILLA s  ON s.CODIGO  = cp.CODIGO_SECCION
LEFT JOIN BIBLIOTECA_COMPONENTE bc ON bc.CODIGO = cp.CODIGO_BIBLIOTECA_COMPONENTE
LEFT JOIN CATALOGO_MAESTRO cm  ON cm.CODIGO = cp.CODIGO_CATALOGO_MAESTRO
WHERE p.IDENTIFICADOR = 'F104'
  AND vp.NUMERO_VERSION = 'v2026.01'
ORDER BY s.ORDEN, cp.ORDEN;

-- 2. Resumen financiero de la declaración (sin leer JSON)
SELECT
    ct.CASILLERO_SRI,
    ct.NOMBRE,
    dvc.VALOR_CALCULADO
FROM DETALLE_VALOR_CONCEPTO dvc
JOIN FORMULARIO_DECLARACION fd ON fd.CODIGO = dvc.CODIGO_FORMULARIO_DECLARACION
JOIN CONCEPTO_TRIBUTARIO ct    ON ct.CODIGO = dvc.CODIGO_CONCEPTO_TRIBUTARIO
WHERE fd.RUC_CONTRIBUYENTE = '1790012345001'
  AND fd.PERIODO_FISCAL    = '2026-01'
ORDER BY ct.CASILLERO_SRI;

-- 3. Ver widgets disponibles en la biblioteca por categoría
SELECT
    tc.NOMBRE_AMIGABLE  AS tipo_primitivo,
    bc.CATEGORIA_UI,
    bc.NOMBRE_UI        AS widget,
    bc.DESCRIPCION,
    bc.CONFIGURACION_DEFAULT_JSON
FROM BIBLIOTECA_COMPONENTE bc
JOIN CATEGORIA_COMPONENTE tc ON tc.CODIGO = bc.CODIGO_CATEGORIA_COMPONENTE
WHERE bc.ACTIVO = 1
ORDER BY bc.CATEGORIA_UI, bc.ORDEN_CATALOGO;

-- 4. Ver reglas condicionales activas del formulario
SELECT
    cp_afectado.CLAVE_UI   AS campo_afectado,
    rc.ACCION,
    rc.CONECTOR_LOGICO,
    rcd.CLAVE_UI_CAMPO_EVALUADO AS campo_disparador,
    rcd.OPERADOR,
    rcd.VALOR_REFERENCIA
FROM REGLA_CONDICIONAL rc
JOIN CAMPO_PLANTILLA cp_afectado ON cp_afectado.CODIGO = rc.CODIGO_CAMPO_PLANTILLA
JOIN REGLA_CONDICIONAL_DETALLE rcd ON rcd.CODIGO_REGLA_CONDICIONAL = rc.CODIGO
JOIN VERSION_PLANTILLA vp ON vp.CODIGO = cp_afectado.CODIGO_VERSION_PLANTILLA
JOIN PLANTILLA p          ON p.CODIGO  = vp.CODIGO_PLANTILLA
WHERE p.IDENTIFICADOR    = 'F104'
  AND vp.NUMERO_VERSION  = 'v2026.01';