🔷 SCRIPT COMPLETO RECONSTRUIDO
/* ================================================================
   ================================================================
   SISTEMA DE DECLARACIONES DINÁMICAS
   SCRIPT COMPLETO RECONSTRUIDO
   ================================================================
   ================================================================ */
🔹 MÓDULO 1: TIPOS DE COMPONENTE
/* ================================================================
   MÓDULO 1: TIPOS DE COMPONENTE
   ================================================================ */

CREATE TABLE CATEGORIA_COMPONENTE (
    CODIGO                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IDENTIFICADOR_TECNICO   VARCHAR2(50)  UNIQUE NOT NULL,
    NOMBRE_AMIGABLE         VARCHAR2(100) NOT NULL,
    ICONO_CSS               VARCHAR2(50),
    PERMITE_CATALOGO        NUMBER(1) DEFAULT 0 CHECK (PERMITE_CATALOGO IN (0,1)),
    PERMITE_HIJOS           NUMBER(1) DEFAULT 0 CHECK (PERMITE_HIJOS IN (0,1)),
    PERMITE_ADJUNTO         NUMBER(1) DEFAULT 0 CHECK (PERMITE_ADJUNTO IN (0,1)),
    ACTIVO                  NUMBER(1) DEFAULT 1 CHECK (ACTIVO IN (0,1))
);

CREATE TABLE BIBLIOTECA_COMPONENTE (
    CODIGO                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_CATEGORIA_COMPONENTE  NUMBER NOT NULL,
    NOMBRE_UI               VARCHAR2(100) NOT NULL,
    DESCRIPCION             VARCHAR2(300),
    CATEGORIA_UI            VARCHAR2(50),
    ICONO_CSS               VARCHAR2(50),
    CONFIGURACION_DEFAULT_JSON CLOB CHECK (CONFIGURACION_DEFAULT_JSON IS JSON),
    ORDEN_CATALOGO          NUMBER DEFAULT 0,
    ACTIVO                  NUMBER(1) DEFAULT 1 CHECK (ACTIVO IN (0,1)),
    CONSTRAINT FK_BC_TIPO FOREIGN KEY (CODIGO_CATEGORIA_COMPONENTE)
        REFERENCES CATEGORIA_COMPONENTE(CODIGO)
);
🔹 MÓDULO 2: METADATA Y CATÁLOGOS
/* ================================================================
   MÓDULO 2: METADATA Y CATÁLOGOS
   ================================================================ */

CREATE TABLE CATEGORIA_PLANTILLA (
    CODIGO      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE      VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(300),
    ICONO_CSS   VARCHAR2(50),
    ORDEN       NUMBER DEFAULT 0,
    ACTIVO      NUMBER(1) DEFAULT 1 CHECK (ACTIVO IN (0,1))
);

CREATE TABLE CATALOGO_MAESTRO (
    CODIGO                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_UNICO            VARCHAR2(50) UNIQUE NOT NULL,
    NOMBRE                  VARCHAR2(100) NOT NULL,
    DESCRIPCION             VARCHAR2(300),
    METADATA_COLUMNAS_JSON  CLOB CHECK (METADATA_COLUMNAS_JSON IS JSON),
    PERMITE_JERARQUIA       NUMBER(1) DEFAULT 0 CHECK (PERMITE_JERARQUIA IN (0,1)),
    ACTIVO                  NUMBER(1) DEFAULT 1 CHECK (ACTIVO IN (0,1)),
    FECHA_CREACION          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_CREADOR         NUMBER,
    CONSTRAINT FK_CM_USR FOREIGN KEY (USUARIO_CREADOR)
        REFERENCES USUARIO(CODIGO)
);

CREATE TABLE CATALOGO_DETALLE (
    CODIGO                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_CATALOGO_MAESTRO NUMBER NOT NULL,
    CODIGO_ITEM_PADRE       NUMBER,
    VALOR_CLAVE             VARCHAR2(100) NOT NULL,
    ETIQUETA                VARCHAR2(200) NOT NULL,
    ATRIBUTOS_EXTRA_JSON    CLOB CHECK (ATRIBUTOS_EXTRA_JSON IS JSON),
    ORDEN                   NUMBER DEFAULT 0,
    ACTIVO                  NUMBER(1) DEFAULT 1 CHECK (ACTIVO IN (0,1)),
    CONSTRAINT FK_CD_MAESTRO FOREIGN KEY (CODIGO_CATALOGO_MAESTRO)
        REFERENCES CATALOGO_MAESTRO(CODIGO),
    CONSTRAINT FK_CD_PADRE FOREIGN KEY (CODIGO_ITEM_PADRE)
        REFERENCES CATALOGO_DETALLE(CODIGO)
);

CREATE INDEX IDX_CD_MAESTRO ON CATALOGO_DETALLE(CODIGO_CATALOGO_MAESTRO);
CREATE INDEX IDX_CD_PADRE   ON CATALOGO_DETALLE(CODIGO_ITEM_PADRE);
CREATE INDEX IDX_CD_CLAVE   ON CATALOGO_DETALLE(VALOR_CLAVE);
🔹 MÓDULO 3: SEMÁNTICA TRIBUTARIA
/* ================================================================
   MÓDULO 3: SEMÁNTICA TRIBUTARIA
   ================================================================ */

CREATE TABLE CONCEPTO_TRIBUTARIO (
    CODIGO              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_PADRE        NUMBER,
    CASILLERO_SRI       VARCHAR2(20),
    NOMBRE              VARCHAR2(300) NOT NULL,
    DESCRIPCION         VARCHAR2(500),
    TIPO_DATO           VARCHAR2(50) DEFAULT 'MONEDA',
    ES_CALCULADO        NUMBER(1) DEFAULT 0 CHECK (ES_CALCULADO IN (0,1)),
    FORMULA_CALCULO     VARCHAR2(500),
    VIGENCIA_DESDE      DATE,
    VIGENCIA_HASTA      DATE,
    ACTIVO              NUMBER(1) DEFAULT 1 CHECK (ACTIVO IN (0,1)),
    CONSTRAINT FK_CT_PADRE FOREIGN KEY (CODIGO_PADRE)
        REFERENCES CONCEPTO_TRIBUTARIO(CODIGO)
);

CREATE INDEX IDX_CT_CASILLERO ON CONCEPTO_TRIBUTARIO(CASILLERO_SRI);
🔷 MÓDULO 4 COMPLETO — SIN OMITIR REGLAS
/* ================================================================
   MÓDULO 4: DISEÑADOR DE PLANTILLAS
   ================================================================ */

CREATE TABLE PLANTILLA (
    CODIGO                      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_CATEGORIA_PLANTILLA  NUMBER NOT NULL,
    IDENTIFICADOR               VARCHAR2(50) UNIQUE NOT NULL,
    NOMBRE                      VARCHAR2(200) NOT NULL,
    DESCRIPCION                 VARCHAR2(500),
    FECHA_CREACION              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_CREADOR             NUMBER,
    CONSTRAINT FK_PLT_CAT FOREIGN KEY (CODIGO_CATEGORIA_PLANTILLA)
        REFERENCES CATEGORIA_PLANTILLA(CODIGO),
    CONSTRAINT FK_PLT_USR FOREIGN KEY (USUARIO_CREADOR)
        REFERENCES USUARIO(CODIGO)
);

CREATE TABLE VERSION_PLANTILLA (
    CODIGO                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_PLANTILLA        NUMBER NOT NULL,
    NUMERO_VERSION          VARCHAR2(20) NOT NULL,
    VIGENCIA_DESDE          DATE NOT NULL,
    VIGENCIA_HASTA          DATE,
    ESTADO                  VARCHAR2(20) DEFAULT 'BORRADOR',
    CONFIG_GLOBAL_JSON      CLOB CHECK (CONFIG_GLOBAL_JSON IS JSON),
    FECHA_CREACION          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_CREADOR         NUMBER,
    CONSTRAINT FK_VER_PLT FOREIGN KEY (CODIGO_PLANTILLA)
        REFERENCES PLANTILLA(CODIGO),
    CONSTRAINT UK_VER_PLT UNIQUE (CODIGO_PLANTILLA, NUMERO_VERSION),
    CONSTRAINT FK_VER_USR FOREIGN KEY (USUARIO_CREADOR)
        REFERENCES USUARIO(CODIGO)
);

CREATE TABLE VERSION_PLANTILLA_HISTORIAL (
    CODIGO                      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_VERSION_PLANTILLA    NUMBER NOT NULL,
    ESTADO_ANTERIOR             VARCHAR2(20),
    ESTADO_NUEVO                VARCHAR2(20) NOT NULL,
    COMENTARIO                  VARCHAR2(500),
    USUARIO_RESPONSABLE         NUMBER NOT NULL,
    FECHA_CAMBIO                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_VPH_VER FOREIGN KEY (CODIGO_VERSION_PLANTILLA)
        REFERENCES VERSION_PLANTILLA(CODIGO),
    CONSTRAINT FK_VPH_USR FOREIGN KEY (USUARIO_RESPONSABLE)
        REFERENCES USUARIO(CODIGO)
);

CREATE TABLE SECCION_PLANTILLA (
    CODIGO                      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_VERSION_PLANTILLA    NUMBER NOT NULL,
    CODIGO_SECCION_PADRE        NUMBER,
    TIPO                        VARCHAR2(30) NOT NULL,
    CLAVE_UI                    VARCHAR2(100) NOT NULL,
    ETIQUETA                    VARCHAR2(200),
    DESCRIPCION                 VARCHAR2(500),
    ORDEN                       NUMBER NOT NULL,
    CONFIG_LAYOUT_JSON          CLOB CHECK (CONFIG_LAYOUT_JSON IS JSON),
    VISIBLE_DEFECTO             NUMBER(1) DEFAULT 1 CHECK (VISIBLE_DEFECTO IN (0,1)),
    CONSTRAINT FK_SEC_VER FOREIGN KEY (CODIGO_VERSION_PLANTILLA)
        REFERENCES VERSION_PLANTILLA(CODIGO),
    CONSTRAINT FK_SEC_PAD FOREIGN KEY (CODIGO_SECCION_PADRE)
        REFERENCES SECCION_PLANTILLA(CODIGO)
);

CREATE TABLE CAMPO_PLANTILLA (
    CODIGO                      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_VERSION_PLANTILLA    NUMBER NOT NULL,
    CODIGO_SECCION              NUMBER,
    CODIGO_BIBLIOTECA_COMPONENTE NUMBER,
    CLAVE_UI                    VARCHAR2(100) NOT NULL,
    ETIQUETA_UI                 VARCHAR2(200) NOT NULL,
    CATEGORIA_COMPONENTE        VARCHAR2(50) NOT NULL,
    ORDEN                       NUMBER NOT NULL,
    ES_OBLIGATORIO              NUMBER(1) DEFAULT 0 CHECK (ES_OBLIGATORIO IN (0,1)),
    ES_VISIBLE                  NUMBER(1) DEFAULT 1 CHECK (ES_VISIBLE IN (0,1)),
    ES_EDITABLE                 NUMBER(1) DEFAULT 1 CHECK (ES_EDITABLE IN (0,1)),
    ANCHO_COLUMNAS              NUMBER DEFAULT 12,
    CODIGO_CATALOGO_MAESTRO     NUMBER,
    PROPIEDADES_UI_JSON         CLOB CHECK (PROPIEDADES_UI_JSON IS JSON),
    CONSTRAINT FK_CP_VER FOREIGN KEY (CODIGO_VERSION_PLANTILLA)
        REFERENCES VERSION_PLANTILLA(CODIGO),
    CONSTRAINT FK_CP_SEC FOREIGN KEY (CODIGO_SECCION)
        REFERENCES SECCION_PLANTILLA(CODIGO),
    CONSTRAINT FK_CP_BIBLIO FOREIGN KEY (CODIGO_BIBLIOTECA_COMPONENTE)
        REFERENCES BIBLIOTECA_COMPONENTE(CODIGO),
    CONSTRAINT FK_CP_CAT FOREIGN KEY (CODIGO_CATALOGO_MAESTRO)
        REFERENCES CATALOGO_MAESTRO(CODIGO),
    CONSTRAINT UK_CP_CLAVE UNIQUE (CODIGO_VERSION_PLANTILLA, CLAVE_UI)
);

CREATE INDEX IDX_CP_VERSION  ON CAMPO_PLANTILLA(CODIGO_VERSION_PLANTILLA);
CREATE INDEX IDX_CP_SECCION  ON CAMPO_PLANTILLA(CODIGO_SECCION);

/* =======================
   REGLAS DE VALIDACIÓN
   ======================= */

CREATE TABLE REGLA_VALIDACION (
    CODIGO          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE          VARCHAR2(100) NOT NULL,
    TIPO            VARCHAR2(30) NOT NULL,
    EXPRESION       VARCHAR2(500),
    MENSAJE_ERROR   VARCHAR2(300),
    REUTILIZABLE    NUMBER(1) DEFAULT 1 CHECK (REUTILIZABLE IN (0,1)),
    ACTIVO          NUMBER(1) DEFAULT 1 CHECK (ACTIVO IN (0,1))
);

CREATE TABLE CAMPO_REGLA_VALIDACION (
    CODIGO_CAMPO_PLANTILLA  NUMBER NOT NULL,
    CODIGO_REGLA_VALIDACION NUMBER NOT NULL,
    ORDEN_EJECUCION         NUMBER DEFAULT 0,
    PARAMETROS_JSON         CLOB CHECK (PARAMETROS_JSON IS JSON),
    PRIMARY KEY (CODIGO_CAMPO_PLANTILLA, CODIGO_REGLA_VALIDACION),
    CONSTRAINT FK_CRV_CAMPO FOREIGN KEY (CODIGO_CAMPO_PLANTILLA)
        REFERENCES CAMPO_PLANTILLA(CODIGO),
    CONSTRAINT FK_CRV_REGLA FOREIGN KEY (CODIGO_REGLA_VALIDACION)
        REFERENCES REGLA_VALIDACION(CODIGO)
);

/* =======================
   REGLAS CONDICIONALES
   ======================= */

CREATE TABLE REGLA_CONDICIONAL (
    CODIGO                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_CAMPO_PLANTILLA  NUMBER NOT NULL,
    ACCION                  VARCHAR2(20) NOT NULL,
    CONECTOR_LOGICO         VARCHAR2(5) DEFAULT 'AND',
    ORDEN                   NUMBER DEFAULT 0,
    CONSTRAINT FK_RC_CAMPO FOREIGN KEY (CODIGO_CAMPO_PLANTILLA)
        REFERENCES CAMPO_PLANTILLA(CODIGO)
);

CREATE TABLE REGLA_CONDICIONAL_DETALLE (
    CODIGO                      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_REGLA_CONDICIONAL    NUMBER NOT NULL,
    CLAVE_UI_CAMPO_EVALUADO     VARCHAR2(100) NOT NULL,
    OPERADOR                    VARCHAR2(20) NOT NULL,
    VALOR_REFERENCIA            VARCHAR2(200),
    CONSTRAINT FK_RCD_REGLA FOREIGN KEY (CODIGO_REGLA_CONDICIONAL)
        REFERENCES REGLA_CONDICIONAL(CODIGO)
        ON DELETE CASCADE
);

/* =======================
   MAPEO CAMPO ↔ CONCEPTO
   ======================= */

CREATE TABLE CAMPO_PLANTILLA_CONCEPTO (
    CODIGO                      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_CAMPO_PLANTILLA      NUMBER NOT NULL,
    CODIGO_CONCEPTO_TRIBUTARIO  NUMBER NOT NULL,
    TIPO_OPERACION              VARCHAR2(20) DEFAULT 'ASIGNACION',
    CONSTRAINT FK_MCC_CAMPO FOREIGN KEY (CODIGO_CAMPO_PLANTILLA)
        REFERENCES CAMPO_PLANTILLA(CODIGO),
    CONSTRAINT FK_MCC_CONCEPTO FOREIGN KEY (CODIGO_CONCEPTO_TRIBUTARIO)
        REFERENCES CONCEPTO_TRIBUTARIO(CODIGO)
);


🔷 MÓDULO 5: EJECUCIÓN (COMPLETO)
/* ================================================================
   MÓDULO 5: EJECUCIÓN
   ================================================================ */

/* ==============================
   FORMULARIO DECLARACIÓN
   ============================== */

CREATE TABLE FORMULARIO_DECLARACION (
    CODIGO                      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_VERSION_PLANTILLA    NUMBER NOT NULL,
    RUC_CONTRIBUYENTE           VARCHAR2(13) NOT NULL,
    PERIODO_FISCAL              VARCHAR2(10) NOT NULL,
    NUMERO_DECLARACION          VARCHAR2(30) UNIQUE,
    ESTADO                      VARCHAR2(20) DEFAULT 'BORRADOR',
    PRIORIDAD                   VARCHAR2(10) DEFAULT 'NORMAL',
    DATOS_JSON                  CLOB CHECK (DATOS_JSON IS JSON),
    USUARIO_CREADOR             NUMBER,
    FECHA_CREACION              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_MODIFICADOR         NUMBER,
    FECHA_MODIFICACION          TIMESTAMP,
    USUARIO_ENVIO               NUMBER,
    FECHA_ENVIO                 TIMESTAMP,
    CONSTRAINT FK_DEC_VER FOREIGN KEY (CODIGO_VERSION_PLANTILLA)
        REFERENCES VERSION_PLANTILLA(CODIGO),
    CONSTRAINT FK_DEC_UCRE FOREIGN KEY (USUARIO_CREADOR)
        REFERENCES USUARIO(CODIGO),
    CONSTRAINT FK_DEC_UMOD FOREIGN KEY (USUARIO_MODIFICADOR)
        REFERENCES USUARIO(CODIGO),
    CONSTRAINT FK_DEC_UENV FOREIGN KEY (USUARIO_ENVIO)
        REFERENCES USUARIO(CODIGO)
);

/* Índices estratégicos */

CREATE INDEX IDX_DEC_RUC
    ON FORMULARIO_DECLARACION(RUC_CONTRIBUYENTE);

CREATE INDEX IDX_DEC_PERIODO
    ON FORMULARIO_DECLARACION(PERIODO_FISCAL);

CREATE INDEX IDX_DEC_ESTADO
    ON FORMULARIO_DECLARACION(ESTADO);

CREATE INDEX IDX_DEC_VERSION
    ON FORMULARIO_DECLARACION(CODIGO_VERSION_PLANTILLA);


/* ==============================
   HISTORIAL DE ESTADOS
   ============================== */

CREATE TABLE DECLARACION_HISTORIAL_ESTADO (
    CODIGO                          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_FORMULARIO_DECLARACION   NUMBER NOT NULL,
    ESTADO_ANTERIOR                 VARCHAR2(20),
    ESTADO_NUEVO                    VARCHAR2(20) NOT NULL,
    COMENTARIO                      VARCHAR2(1000),
    USUARIO_RESPONSABLE             NUMBER NOT NULL,
    FECHA_CAMBIO                    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_DHE_DEC FOREIGN KEY (CODIGO_FORMULARIO_DECLARACION)
        REFERENCES FORMULARIO_DECLARACION(CODIGO),
    CONSTRAINT FK_DHE_USR FOREIGN KEY (USUARIO_RESPONSABLE)
        REFERENCES USUARIO(CODIGO)
);

CREATE INDEX IDX_DHE_DEC
    ON DECLARACION_HISTORIAL_ESTADO(CODIGO_FORMULARIO_DECLARACION);


/* ==============================
   DETALLE VALOR CONCEPTO
   ============================== */

CREATE TABLE DETALLE_VALOR_CONCEPTO (
    CODIGO_FORMULARIO_DECLARACION   NUMBER NOT NULL,
    CODIGO_CONCEPTO_TRIBUTARIO      NUMBER NOT NULL,
    VALOR_CALCULADO                 NUMBER(19,4),
    FECHA_CALCULO                   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CODIGO_FORMULARIO_DECLARACION, CODIGO_CONCEPTO_TRIBUTARIO),
    CONSTRAINT FK_DVC_DEC FOREIGN KEY (CODIGO_FORMULARIO_DECLARACION)
        REFERENCES FORMULARIO_DECLARACION(CODIGO)
        ON DELETE CASCADE,
    CONSTRAINT FK_DVC_CON FOREIGN KEY (CODIGO_CONCEPTO_TRIBUTARIO)
        REFERENCES CONCEPTO_TRIBUTARIO(CODIGO)
);

CREATE INDEX IDX_DVC_CONCEPTO
    ON DETALLE_VALOR_CONCEPTO(CODIGO_CONCEPTO_TRIBUTARIO);


/* ==============================
   OBSERVACIONES
   ============================== */

CREATE TABLE DECLARACION_OBSERVACION (
    CODIGO                          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_FORMULARIO_DECLARACION   NUMBER NOT NULL,
    CODIGO_CAMPO_PLANTILLA          NUMBER,
    TIPO                            VARCHAR2(20) DEFAULT 'GENERAL',
    MENSAJE                         VARCHAR2(1000) NOT NULL,
    RESUELTO                        NUMBER(1) DEFAULT 0 CHECK (RESUELTO IN (0,1)),
    USUARIO_CREADOR                 NUMBER NOT NULL,
    FECHA_CREACION                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_RESOLUTOR               NUMBER,
    FECHA_RESOLUCION                TIMESTAMP,
    CONSTRAINT FK_DO_DEC FOREIGN KEY (CODIGO_FORMULARIO_DECLARACION)
        REFERENCES FORMULARIO_DECLARACION(CODIGO),
    CONSTRAINT FK_DO_CAMPO FOREIGN KEY (CODIGO_CAMPO_PLANTILLA)
        REFERENCES CAMPO_PLANTILLA(CODIGO),
    CONSTRAINT FK_DO_UCRE FOREIGN KEY (USUARIO_CREADOR)
        REFERENCES USUARIO(CODIGO),
    CONSTRAINT FK_DO_URES FOREIGN KEY (USUARIO_RESOLUTOR)
        REFERENCES USUARIO(CODIGO)
);

CREATE INDEX IDX_DO_DEC
    ON DECLARACION_OBSERVACION(CODIGO_FORMULARIO_DECLARACION);


/* ==============================
   ADJUNTOS
   ============================== */

CREATE TABLE DECLARACION_ADJUNTO (
    CODIGO                          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_FORMULARIO_DECLARACION   NUMBER NOT NULL,
    CODIGO_CAMPO_PLANTILLA          NUMBER,
    NOMBRE_ORIGINAL                 VARCHAR2(255) NOT NULL,
    NOMBRE_ALMACENADO               VARCHAR2(255) NOT NULL,
    RUTA_ALMACENAMIENTO             VARCHAR2(500) NOT NULL,
    MIME_TYPE                       VARCHAR2(100),
    TAMANIO_BYTES                   NUMBER,
    HASH_SHA256                     VARCHAR2(64),
    FECHA_CARGA                     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_CARGA                   NUMBER,
    CONSTRAINT FK_DA_DEC FOREIGN KEY (CODIGO_FORMULARIO_DECLARACION)
        REFERENCES FORMULARIO_DECLARACION(CODIGO)
        ON DELETE CASCADE,
    CONSTRAINT FK_DA_CAMPO FOREIGN KEY (CODIGO_CAMPO_PLANTILLA)
        REFERENCES CAMPO_PLANTILLA(CODIGO),
    CONSTRAINT FK_DA_USR FOREIGN KEY (USUARIO_CARGA)
        REFERENCES USUARIO(CODIGO)
);

CREATE INDEX IDX_DA_DEC
    ON DECLARACION_ADJUNTO(CODIGO_FORMULARIO_DECLARACION);